### ISSUE TITLE
Bug Mision enmiendas

### ISSUE THREAD

**Issue by smycer** [Demonid/BugTracker#1]
Demonid

Por favor arregla la misión enmiendas de la cadena para Reputación de hijos de Hodir, que no aparece el NPC Fjorn para poder matarlo y completar la mision.

Gracias

**Comment by el-druida** [comment]
Por favor, incluya ID de la mision asi como ID del npc involucrado

**Comment by Demonid** [comment]
@smycer Esta noche se han realizado algunas modificaciones, podrias probar nuevamente ?
