### ISSUE TITLE
Bug Habilidad "Levantar a muerto" del Caballero de la muerte

### ISSUE THREAD

**Issue by aemcae** [Demonid/BugTracker#10]
Hola, como lo comente via ticket, la habilidad de mi Caballero de la muerte "Levantar a muerto" esta bug, al usar ducha habilidad debería invocar a un necrofago lo cual no lo hace, simplemente hace la animación de la habilidad pero no invoca ningún necrofago.
Cabe aclarar que este bug no se les presenta a todos , pues in-game he visto a varios usando al necrofago.

Reinicie el juego varias veces, borre cache, reinicie los talentos, nada ha funcionado hasta el momento, este problema persiste incluso si cambio a la segunda rama de talentos.

Mi caballero de la muerte es de la facción Alianza, raza humano.

**Comment by OldieButGoldie** [comment]
Hola, el fix está aplicado en desarrollo y estará activo en breves, solucionamos asimismo un problema similar en brujos. 

Gracias por el reporte
