### ISSUE TITLE
Alarido Psiquico en sacerdote bug

### ISSUE THREAD

**Issue by godlike93** [Demonid/BugTracker#11]
Al usar fear sobre el enemigo, no se le puede lanzar ningún hechizo porque su posición que se ve no es la real. Al terminar el fear el enemigo está en otro lado

**Comment by Demonid** [comment]
Buenas!

Este problema es generico en si, aplica a cualquier tipo de fear tanto el del brujo como el de guerrero y lamentablemente es bastante dificil de reparar, le echaremos in vistazo pero no sera algo rapido, Saludos!

**Comment by psicopata** [comment]
asd
