### ISSUE TITLE
tehno

### ISSUE THREAD

**Issue by Tehno123** [Demonid/BugTracker#12]
Hola como le dije tengo un problema con mi dk cuando uso levantar muerto no aparece el pet  ya lo intente olvidando talentos pero no funcionó

**Comment by el-druida** [comment]
https://github.com/Demonid/BugTracker/issues/10

**Comment by Demonid** [comment]
Buenas! Ayer se hizo un mantenimiento donde en principio se arreglo el fallo que mencionas, podrias probar de nuevo y comentarnos? Saludos!

**Comment by Tehno123** [comment]
Si esta todo normal gracias
