### ISSUE TITLE
Bug hechizos a través de un muro

### ISSUE THREAD

**Issue by godlike93** [Demonid/BugTracker#13]
Mientras hacía arenas, un sacerdote me podía quemar el maná estando escondido del otro lado del muro y también en esta misma arena, el mismo sacerdote casteaba sus salvas de Penitencia hacia su compañero traspasando el muro. Arreglen esto cuanto antes por favor
![ruins-lordaeron-arena-wow-3](https://cloud.githubusercontent.com/assets/28567680/25860541/77ea3828-34a7-11e7-8c4d-05d599854513.jpg)

**Comment by Demonid** [comment]
Lamentablemente y por mas ilógico que parezca, esto es Blizzlike, hay múltiples temas rondando sobre esto, aquí tienes incluso un vídeo grabado en el oficial:

https://www.youtube.com/watch?v=JX2q2Vu0_t0

Acá tienes mas información aun:

https://us.battle.net/forums/en/wow/topic/2325616793
http://wowwiki.wikia.com/wiki/Line_of_sight
http://wiki.angry.com.au/display/WOW/Line+of+Sight+Pull

**Comment by OldieButGoldie** [comment]
Duplicado #2
