### ISSUE TITLE
Bug (La mision de Foso de Saron) Tyranus debe morir

### ISSUE THREAD

**Issue by s1n1estr0** [Demonid/BugTracker#14]
Hola, seré directo....la misión de Foso de Aron, esta bug la parte en la que se tiene q entregar a Jaina....una ves muerto tyranus...debería de poder entregarse a Jaina, pero no se puede ya que ella sigue peleando con los mobs...y según nos dijo un GM, deberiamos poder matar a esos mobs, pero no podemos porque los vemos como aliados....y al final terminan matándola a Jaina...haciendo imposible poder cumplir esa misión...Ya vamos como 4 días con estos problemas...haber si hacen algo...!! porque e visto que en la horda no tiene ningún problema.

**Comment by OldieButGoldie** [comment]
Duplicado #8

**Comment by Demonid** [comment]
Aprovecho para comentar que se hicieron ajustes a la misión ayer por la noche, podrías probar nuevamente y crear un nuevo issue en caso de ser necesario? Saludos!
