### ISSUE TITLE
Presunto xploit de subasta. Mutliplicar items.

### ISSUE THREAD

**Issue by rxclplop** [Demonid/BugTracker#15]
Bueno, básicamente el bug consiste en poner es subasta items stackeables o no a un precio absurdo (para que nadie los compre) y una vez pasan las 24 horas de la subasta recibes nuevamente los items en el buzón de mensajes. Si en la devolución tienes un pack x20 de lo que sea y tienes las bolsas llenas, no recibiras el item y se quedará en el buzón como mensaje leído. AL parecer cuando cambian de core, pasa algo raro con el buzón de mensajes y los items que no recibiste por bolsas llenas se duplican.

Algo parecido ocurre con el set que da la ardilla 2.0, pero dicho bug no requiere el cambio de core. Simplemente recibes la bolsa de regalo con 3 o 4 espacios en tus mochilas, cojes de cada bolsa de regalo los items dejando solo uno en cada bolsa, y como no puedes recibir más por tus mochilas llenas, se cierran y debes loguear. Cuando entras nuevamente al juego y abres la bolsa de las armas pvp que te ragalan, salen nuevamente las que ya habías recogido, osea se duplican.

Lo mismo ocurría en su momento con las pociones de las bolsas cuando subes a lvl 80, se duplicaban los items cuando reclamas una poción y solo tienes espacio para un item en tu inventario, al reloguear abrías la bolsa de regalo y la poción se duplicaba.

Pd: El bug de la subasta no tengo ahora mismo como probarlo, el del set de La Ardilla 2.0 sí y es muy facil de hacer.

**Comment by OldieButGoldie** [comment]
Desconozco el estado del viejo core en cuanto a bugs, pero con el que se está haciendo desarrollo no ocurre.

El bug de la ardilla tampoco he visto que ocurra, al abrir las bolsas luego de reloguear sólo está presente el item que faltaba lootear,

**Comment by rxclplop** [comment]
Si deseas puedes mirar mi inventario para corroborar lo del bug de la ardilla, tengo duplicados los abalorios de maestro de batalla, las dagas del pícaro, dos escudos y dos dagas con el chaman al igual que el totem. Lo único que no se pudo duplicar es el medallón de la alianza u horda por que el juego no lo permite.

**Comment by Demonid** [comment]
@rxclplop Podrías confirmar si los fallos que reportas siguen ocurriendo en el core actual?

**Comment by rxclplop** [comment]
Ayer  confirmé que el bug persiste, pues al momento de loguear con mi druida y al lotear de nuevo la bolsa de armas pvp y abalorios, salieron todos los items que ya había loteado previamente.

**Comment by Demonid** [comment]
@rxclplop Me parece que lo que paso con tu Druida es simplemente que el loot ya estaba regenerado en el core viejo y recién ahora que lo tomaste se te soluciono, podrías volver a intentar conseguir el loot de esa bolsa?

Btw, el tema de la subasta, puedes confirmar que aun existe?

**Comment by rxclplop** [comment]
Creo que tienes razón con lo lo que dijiste respecto del core viejo, ahora mismo no se reproduce el fallo.
Lo de la subasta no podría confirmarlo si no se cambia de core, creo que solamente así funciona. Muchas gracias por prestarle atención a todo.

**Comment by Demonid** [comment]
Perfecto, si encuentras cualquier cosa mas nos la reportas, gracias!
