### ISSUE TITLE
Problema con el autolearn

### ISSUE THREAD

**Issue by Hades0040** [Demonid/BugTracker#17]
Soy nivel 71 y no tengo aprendido equitacion de vuelo, y tampoco puedo aprender, tampoco tengo ninguna montura voladora

**Comment by Demonid** [comment]
Gracias por reportar, intentaremos solucionarlo pronto

**Comment by OldieButGoldie** [comment]
Problema solucionado en DEV, será aplicado en el siguiente reinicio.

Un saludo
