### ISSUE TITLE
Bugs de TOC10h

### ISSUE THREAD

**Issue by efroilan** [Demonid/BugTracker#18]
## en bestias
1er Boss: el fuego que lanza el primero se supone que lo lanzan los vasallos cuando salen, y los esta lanzando sin salir vasallos, lanza 6 o 7 fuegos antes q salga un vasallo, aparte el fuego tiene mucho rango de daño. es decir, te mueves del fuego y tienes que alejarte mucho para que deje de pegarte y montarte cargas. (tiene un rango bastante fuera de lo normal)

3boss (aullahielo): el cargar casi siempre mata a alguien instakill asi te alejes asi corras como es, casi siempre mueres.

## Anub arak:

A veces se buguea cuando se sumerge y no persigue. al parecer se bugueo con la pet del DK.

**Comment by el-druida** [comment]
Lamento comunicarle que el funcionamiento actual de Gormok es el correcto. Las bombas de fuego las lanzan los snobold desde su lomo. Sobre el daño del fuego es el correcto para la modalidad HERO.

**Comment by OldieButGoldie** [comment]
Si bien el fuego es correcto, seguimos revisando la falla del rango de daño.

**Comment by efroilan** [comment]
perfecto.. sorry pense que era bug eso de q los lanzaran asi. pero todo bien entonces..

**Comment by Demonid** [comment]
Todos los fallos han sido solucionados, si encuentras mas por favor reportalos.
