### ISSUE TITLE
{Bug, cazador hacerse el muerto}

### ISSUE THREAD

**Issue by kevinpatrick** [Demonid/BugTracker#19]
Buenas, cuando me hago el muerto con el cazador, el poder no queda en cd, sino que parece que es utilizable aún pero en realidad está en cd y no puedo ver el tiempo de reutilización del poder.

**Comment by rxclplop** [comment]
Lo mismo sucede con cold blood de los rogues

**Comment by OldieButGoldie** [comment]
Hola, por lo visto es algo visual según comentan, ya que en sí, deben esperar el cooldown. Si usas addons ponlos aquí, alguno podría estar interfiriendo.

**Comment by Demonid** [comment]
@kevinpatrick Podrías dejarnos los pasos para reproducir el fallo o mostrarnos en un pequeño vídeo sin addons el fallo en cuestión? Gracias!

**Comment by Demonid** [comment]
Debido a que no se dejaron los pasos para revisar el fallo, tocara cerrarlo, pueden abrir el tema nuevamente si encuentran una forma de reproducir el fallo.
