### ISSUE TITLE
Cazadores sin linea de visión - disparar a través de paredes.

### ISSUE THREAD

**Issue by Zlorak** [Demonid/BugTracker#2]
Los cazadores pueden disparar a un objetivo que se encuentre detrás de una pared/muro, esto se puede ver constantemente en campos de batalla que es donde aparentemente más se reproduce el bug. 

Esto suele suceder con algunas texturas tales como los troncos cortados en Garganta Grito de Guerra o las columnas destrozadas en la Base Draenei de Ojo de la Tormenta.

**Comment by OldieButGoldie** [comment]
Se está investigando el tema, pero por lo visto en el oficial también ocurría: 
https://www.youtube.com/watch?v=EFyqQ96AAHg&feature=youtu.be&t=8m30s

**Comment by Demonid** [comment]
Lamentablemente y por mas ilógico que parezca, esto es Blizzlike, hay múltiples temas rondando sobre esto, aquí tienes incluso un vídeo grabado en el oficial:

https://www.youtube.com/watch?v=JX2q2Vu0_t0

Acá tienes mas información aun:

https://us.battle.net/forums/en/wow/topic/2325616793
http://wowwiki.wikia.com/wiki/Line_of_sight
http://wiki.angry.com.au/display/WOW/Line+of+Sight+Pull
