### ISSUE TITLE
{Bug, cólera de bestias del cazador bestias}

### ISSUE THREAD

**Issue by kevinpatrick** [Demonid/BugTracker#20]
Buenas, cuando mi pet está mureandome en arenas ya sea en columna, el poder de cólera de bestias no se me activa, solo se activa cuando estoy al lado de mi pet; cosa que no debería pasar así ya que cólera de bestias se le otorga directamente al portador.

**Comment by Demonid** [comment]
Buenas, en principio esta habilidad esta funcionando correctamente para la versión 3.3.5a

Fue hasta el parche 5.2.0 (Mist of Pandaria) donde Bestial Wrath dejo de verse afectada por lineas de visión.

Mists-Logo-Small Patch 5.2.0 (5-Mar-2013): Bestial Wrath may now be activated when there is no line of sight to the Hunter's pet.
http://wowwiki.wikia.com/wiki/Bestial_Wrath
