### ISSUE TITLE
[Bug] Shaman - Camino de espiritu 

### ISSUE THREAD

**Issue by Cruelity** [Demonid/BugTracker#21]
La skill ''Camino de espiritu'' que te otorga Sprint de 60% y Elimina todo efecto de ralentizar/root, Se vuelve inutilizable para el portador cuando los lobos estan tras un muro (columnas de arena)

**Comment by OldieButGoldie** [comment]
El bug fue reparado en DEV, será aplicado en el próximo reinicio.

Gracias por el reporte.
