### ISSUE TITLE
{Bug, Cólera de bestias} (Video explicación)

### ISSUE THREAD

**Issue by kevinpatrick** [Demonid/BugTracker#22]
Buenas, aquí tengo la explicación en video del bug de cólera de bestias como debería ser.
El primer video es del server ArenaTournament y el segundo es del servidor WoW-Asura espero les sea de ayuda.
- Primer video de AT https://youtu.be/d3cDmw7QFR4
- Segundo video de WoW-Asura https://youtu.be/s1w2byRofao

Como vemos en el video número 1 la skill Cólera de bestias no se debe activar si la pet está mureando a su dueño en este caso al cazador.
Y en el video número 2 deja cd y no se activa la skill.

Con esta explicación espero se haga una mejora, ya que lo hago para que el server progrese y sea muy entretenido para todos, gracias.

**Comment by el-druida** [comment]
https://github.com/Demonid/BugTracker/issues/20

**Comment by el-druida** [comment]
Videos de servidores privados no cuentan como fuente, solo el oficial en su version 3.3.5a.

**Comment by valentincabrera792** [comment]
Yo creo que toca tener en cuenta WARMANE como el único server con el fix pvp mas completo al blizz.
Seria muy dificil buscar video por video (de los antiguos jugadores del ofi) y ver el momento exacto en que usa la spell en la condicion indicada bajo la circunstancia determinada... Como esta propuesto este post es facil, visible y verificable.

**Comment by OldieButGoldie** [comment]
#20 reporta cólera como no funcional al estar fuera de linea de visión con la pet, lo cual es blizzlike hasta Mists of Pandaria.

Este es otro bug sin embargo, el funcionamiento es correcto (no se activa); pero no debería dar el cooldown.

**Comment by Demonid** [comment]
Ya estamos trabajando en una solución, dentro de poco estará en el reino live, saludos!
