### ISSUE TITLE
Bug , No sube la  Equitacion en los Caballero de la Muerte.

### ISSUE THREAD

**Issue by Hilaridiego** [Demonid/BugTracker#23]
Hola, el servidor cuenta con la ayuda de las equitaciones . aprendizaje de las habilidades automáticamente  en las razas y ambas facciones,  recientemente  llegue 80 con mi dk Hilari, ya al principio nivel 62 la equitación se quedo 75/150 , no solo soy yo también el pj de mi amigo, no se si también si este bug o error ocurre con los demás caballeros de la muerte . recién creados .Trate de aprender la equitación  con el instructor pero no resulta. Ahora soy 80 y no puedo volar en Rasganorte, estoy atascado.  Necesito que lo arreglen lo antes posible al menos solo en mi personaje , como en los otros usuarios con las equitaciones automáticas. Espero su respuesta y solución, lo mas pronto.
Me despido y Gracias por su atención.

**Comment by OldieButGoldie** [comment]
Duplicado #17, el bug ya está corregido, en el próximo reinicio se aplicarán los cambios
