### ISSUE TITLE
BUG brujo "afliccion inestable y corrupcion"

### ISSUE THREAD

**Issue by akatalandia** [Demonid/BugTracker#24]
Buenas, eh estado viendo q el daño q hacen estos poderes no son los correctos lo prove y nada... un ejemplo mi afliccion inestable hace un daño de 1.4k por defecto y al momento de darle solo hace  1.1  o 900 de daño enserio es demaciado bajo....

**Comment by Demonid** [comment]
Y en que te estas basando para concluir que ese daño es el que deberías hacer ?

Podrías subir capturas de pantalla y/o fuentes? Saludos!

**Comment by el-druida** [comment]
Y con quien o que estas testeando, un jugador, un muñeco, un jugador con ropa o sin equipo?

**Comment by akatalandia** [comment]
https://www.youtube.com/watch?v=bvJXCpT6oZY

**Comment by akatalandia** [comment]
el equipo q tengo es 4 parte t9 ah y mire q me olvide del bonus q da el tier, otra cosa corrupcion por DOT deberia de pegar mas muchooo mas no 1.4 k pfff igual afliccion inestable... considerando q el poder con hechisos potencia obviamente mis hechisos pero es como si no tubiera nada.... aumenten la calidad de video

**Comment by akatalandia** [comment]
respondiendo a tu pregunta el druida lo eh testeado con el MJ en el muñeco y con los mobs bichos de por hay el daño es el mismo

**Comment by Demonid** [comment]
He visto el vídeo pero sigo sin entender de donde sacas que debe pegar mas, acabo de mover tu Pj a mi cuenta para hacer pruebas de daño y comparándolas con el daño mostrado por DrDamage, y todo tu daño esta dentro de la media.

Por ejemplo:

Según el Addon, tu afflicion inestable debería estar haciendo lo siguiente de daño:

http://i.imgur.com/LECIYdA.png

Una media de 5031 de daño sin críticos.

Y esto es lo que ha pegado tu afflicion inestable:

http://i.imgur.com/kvraqQP.png

5 Ticks de 1005 lo cual equivale a 5,025, que entra dentro del rango de error del addon.

En principio el daño de tus habilidades es el correcto.

Si en otro core u otro server pegabas mas, es porque estaba bug y ahora estas viendo el daño Blizzlike de la habilidad.

**Comment by OldieButGoldie** [comment]
> el equipo q tengo es 4 parte t9 ah y mire q me olvide del bonus q da el tier, otra cosa corrupcion por DOT deberia de pegar mas muchooo mas no 1.4 k pfff igual afliccion inestable... considerando q el poder con hechisos potencia obviamente mis hechisos pero es como si no tubiera nada.... aumenten la calidad de video

Sólo por curiosidad, cuánto tienes de poder con hechizos?

**Comment by akatalandia** [comment]
2482 sp, ahora nose como mandar fotos.... el principal spell q tiene el brujo afliccion para hacer daño es la "corrupcion" pero hay comprare entre el CENSURADO y ASURA, en los anteriores la corrupcion siempre hace mas daño q la descarga de las sombras seguido por afliccion inestable pero aqui hago un 42% de daño con descarga de sombras seguido con 37% de corrupcion "siendo la principal" y  14% de afliccion inestable...  si ni aun tengo tanto Spell power todavia tengo recien 2482, lo cual mi el equipo T9 esta como deberia pues el bonus q da potencia corrupcion y afliccion inestable.... digo esto porq mi daño bajo demaciado hago el mismo daño q hacia con mi valeroso y no puede ser asi q ya tengo mas equipo mucho mas

**Comment by akatalandia** [comment]
pero por lo q vi "SERVIDORES PRIVADOS NO CUENTAN" okey entonces q hago porq eh jugado brujo soy main brujo... creo q soy el unico q tiene 4 brujos solo porq me conosco al look como es y como siempre eh jugado, pero ahora q veo el daño mi principal Spell con el set t9 deberia ser "corrupcion" pero esta muy por debajo de la descarga de las sombras... y es facil darse cuenta porq en tantos años q me digan q eh capeado mal, o q hago algo mal pues no, es como si a hellsing yo le enseria a jugar con sus pj principales "jamas" lo haria...

**Comment by akatalandia** [comment]
por otra parte se q los MJ's nunca te daran la razon ala primera, como el post de colera de las bestias "creo" y le dijeron q no cuenta bueno entonces q hago, como demuestro que esos hechisos estan mal, no sabre sobre la base de datos ni nada de eso o de otros personajes o clases, pero de mi clase estoy mas q seguro... por la experiencia q tengo

Gracias por su tiempo

**Comment by oscaracho** [comment]
realmente esta bug el brujo. recuerdo que antes de se implementara toc siempre veía a brujos aflicción con mayor daño en los dot de corrupcion. pero ahora cuando veo brujos en las raid por mas armados que esten no hacen mucho dps

**Comment by Demonid** [comment]
@akatalandia Las pruebas que te he mostrado son usando un Addon que fue creado en el oficial precisamente para saber el daño exacto de tus habilidades tomando en cuenta talentos, coeficientes, etc etc.

Usar otros servidores privados como "Prueba" es tontería, y mucho menos esos 2 que mencionas que a lo largo de los años han sido conocidos por tener cientos de Bugs y nulo desarrollo, si quieres usar un privado como "Prueba", al menos que sea Blackrock de Warmane, que es el equivalente a Arena Tournament, pero fuera de ese el resto no podrían siquiera llegar a tomarse en cuenta.

Te dejo el Link del Addon para que hagas las pruebas por ti mismo: http://www.mediafire.com/file/a34jnojublyag49/DrDamage.rar

Dicho esto, el reporte ha sido revisado y se ha contestado con pruebas que el daño de las habilidades esta dentro del margen de daño Blizzlike por lo que daremos como invalido el reporte y sera cerrado hasta que se encuentran mas pruebas, te he dejado un Link con el Addon que calcula los daños de cada habilidad basado en tus talentos y poder con hechizos, echale un vistazo.

Recuerda que el WoW es un juego donde las matemáticas y especialmente las formulas lo dicen todo, y por ende los resultados del daño de tus habilidades siempre serán similares a lo que el addon te muestra.

Saludos!

**Comment by OldieButGoldie** [comment]
> por otra parte se q los MJ's nunca te daran la razon ala primera, como el post de colera de las bestias "creo" y le dijeron q no cuenta bueno entonces q hago, como demuestro que esos hechisos estan mal, no sabre sobre la base de datos ni nada de eso o de otros personajes o clases, pero de mi clase estoy mas q seguro... por la experiencia q tengo

El ticket sigue abierto... no fue desestimado, incluso escribí sobre el mismo: https://github.com/Demonid/BugTracker/issues/22#issuecomment-300368833

Ahora bien, volviendo al tema del ticket, procedamos a calcular Corrupción con 2482 SP y el bonus de T9:

Corrupción potenciada: aumenta la contribución total de SP un 36%, ya que corrupción tiene 6 ticks, calcularemos el daño por tick: corrupción potenciada aumenta la contribución de SP de cada 'tick' un 6%

Corrupción (rango 10) - Daño base por 'tick': 180
Corrupción escala con 20% de tu SP total: (+6% con Corrupción potenciada (rango 3))

2482 SP  x 26 / 100 = 645,32

daño base + contribucion sp = 180 + 645,32 = 825,32
Bonus T9 4P (aumenta 10% el daño de inmolar, corrupción y aflicción inestable) 

825,32 + 10% = 907,852

Corrupción mejorada (rango 5) -> aumenta 10% el daño de corrupción

907,852 + 10% = 998,6372

Contagio (rango 5) -> aumenta 5%

998,6372 + 5% = 1048,56906

Abrazo de las sombras, otro 5%

1048,56906 + 5% = 1100,997513

Si haces "1.1" de daño por tick, con 2482 SP, se corresponde con el resultado obtenido manualmente, puedo concluir que el spell funciona correctamente.

**Comment by OldieButGoldie** [comment]
Dando por respondido el ticket, cierro
