### ISSUE TITLE
Para Cuando Toc5!!!

### ISSUE THREAD

**Issue by lunas123** [Demonid/BugTracker#25]
Hoy en día  la banda principal es TOC,  lo cual significa que su heroica debe estar funcionando, Desde que se abrió TOC la mazmorra esta deshabilitada. 
La gente pide a gritos TOC5 o eso es lo que veo.

**Comment by akizara** [comment]
Sii, por favor que la habiliten :D

**Comment by el-druida** [comment]
Para estar dicha mazmo activa, las facciones ya no deberian mezclarse

**Comment by Demonid** [comment]
@el-druida Esto no es verdad, el Crossfaction en Raids no afecta en nada a la mazmorra.

Contestando a la pregunta de para cuando ToC5, subiré una versión funcional para el fin de semana, no estará perfecta, pero estará funcional.

**Comment by OldieButGoldie** [comment]
Buenas, la mazmorra está implementada con el reinicio del dia de la fecha.

Un saludo
