### ISSUE TITLE
DK - Arma de runa danzante. (bug)

### ISSUE THREAD

**Issue by MuWoW** [Demonid/BugTracker#27]
Buenas!

Reporto el poder "Arma de Runa danzante" (rama Sangre - DK) : 

Al activarse el arma "no ataca". el recount o skada no calcula el daño que debería ser aumentado con el hechizo "Arma de Runa danzante" (50% de daño del arma). Tampoco calcula el Combat Log, solamente reporta la activación del hechizo mas NO el daño del "arma de runa danzante" ni un aumento en el daño blanco (melee físico) del 50% como se espera.

Además el hechizo "arma de runa danzante" no proyecta las animaciones correspondientes (por ende da a entender que el arma invocada NO ATACA)
1: el arma no es un objeto targeteable.
2: no tiene movimiento ni realiza algún daño o animación de daño o mas simple... "no ataca ni muestra los numeritos naranjas con cada ataque que lo haría cualquier pet/item invocado que produzca daño".

1.- Recount y Skada con gráfica a tiempo real donde el daño blanco mas pasivos de DK sangre son mostrados (antes de activar el "arma de runa danzante").

http://imgur.com/fzM3z3e

2.- Recount y Skada con gráfica a tiempo real donde el daño blanco mas pasivos de DK sangre son mostrados (EN EL INSTANTE Y DESPUÉS de activar el "arma de runa danzante").

http://imgur.com/FwJmal0

(NÓTESE QUE EL ARMA PARECIESE QUEDAR ESTÁTICO YA QUE EN LA IMAGEN SE VERÍA AL MENOS EN UNA POSICIÓN DE ATAQUE O IMPACTANDO AL OBJETIVO).

3.- Combat Log donde muestra el daño blanco mas pasivos de DK sangre antes de activar "arma de runa danzante".

http://imgur.com/D0JvzJw

4.- Combat Log donde muestra el daño blanco mas pasivos de DK sangre en el momento y después de activar "arma de runa danzante".

http://imgur.com/IeKIyD1

El tiempo de casteo es correcto (12 segs mas o menos), pero la falta de animaciones de "ataque" del hechizo, mas la falta de "daño" del hechizo (que lo he notado ingame, por experiencia en otros servers incluyendo warmane, lcv, antares, wla, rean, wowarg, core y hasta en reinos iberos) me hacen pensar que el hechizo esta bug ya que en otras situaciones el "arma de runa danzante" ataca, y hace daño de pet (numeritos naranjas). Una revisadita por favor :D ! mil gracias por el esfuerzo!

**Comment by Demonid** [comment]
Gracias por reportar, el fallo ha sido confirmado y esta en espera de una futura solución.

**Comment by MuWoW** [comment]
Mil gracias!! jeje dk sangre es una rama exotica y bella tanto en pve como en pvp :v estaré viendo mas detalles en las clases por si encuentro otros bugs q reportar v: mil gracias!
