### ISSUE TITLE
Misión: "El Drakkensryd" (ID=12886) Bug.

### ISSUE THREAD

**Issue by MuWoW** [Demonid/BugTracker#28]
Buenas!

Reporto la mision ID=12886 "El Drakkensryd" como bug, pero pasable actualmente en WoWAsura. 

Como funciona ahora: La misión te monta en un protodraco para mandarte directamente al "Templo de las Tormentas " con el item "Arpón Hyldnir" (item=41058) en inventario. En el "Templo de las Tormentas" habrán un grupo grande de protodracos montados con "Jinete de dracos" donde tendrías que usar el Arpón para pasarte de protodraco en protodraco derrotando a las "Jinetes de dracos" mientras andan en pleno vuelo. LO CUAL ACTUALMENTE ES CASI IMPOSIBLE ya que no se puede atacar a las "Jinetes de dracos" como es debido (daño melee por estar en distancia mínima ya que montan el mismo protodraco). CON CIERTA SUERTE al moverse de protodraco en protodraco y atacando en pleno aire a una "Jinete de draco" se puede targetearle (Cosa q no se puede normalmente estando en distancia mínima) y SOLAMENTE se les puede atacar con un daño a DISTANCIA (inclusive estando a distancia mínima / melee). Matando a 10 "Jinetes de dracos" se da por terminada la misión.

Como debería funcionar:  La misión te monta en un protodraco para mandarte directamente al "Templo de las Tormentas " con el item "Arpón Hyldnir" (item=41058) en inventario. En el "Templo de las Tormentas" habrán un grupo grande de protodracos montados con "Jinete de dracos" donde tendrías que usar el Arpón para pasarte de protodraco en protodraco derrotando a las "Jinetes de dracos" mientras andan en pleno vuelo. Se podría atacar con MELEE tranquilamente o ataques a distancia que incluyen tb distancia mínima (como toque helado, espiral de la muerte entre otros) para así terminar facilmente la misión atacando a las "Jinetes de dracos" normalmente. Matando a 10 "Jinetes de dracos" se da por terminada la misión.

Acá dejo el video correspondiente de un servidor X donde indica correctamente como debería funcionar (capturar en pantalla, o sacar un video en WoWAsura resulta casi imposible por ser una rama de misiones que ya completé antes de reportar este bug). 

https://www.youtube.com/watch?v=oCcyIi7sqZE

PD: en Wowhead se ve claramente que aún sigues con el disfraz de vyrkul (que adquieres a medida que haces la cadena de misiones de Hodir) : 

http://imgur.com/VWeM416

Sin embargo en WoWAsura no tienes el disfraz.

Reporto esta misión por ser de VITAL IMPORTANCIA para sacar enchants de hombros (ya que esta misión es parte de la cadena de misiones que habilitan la reputación "HIJOS DE HODIR" para que se pueda habilitar la zona "Dun Niffelem" para adquirir diarias (para subir repu) como también para subir la reputación a "Neutral" desde "odiado". (una cadena larguísima de mas de 25 misiones). Sin esta misión no se puede acceder a "Hijos de Hodir" como es debido y por lo tanto: el intendente de Hijos de Hodir queda inhabilitado (adiós enchants de hombros / bolsas / mamuts lanudos) :v 

Gracias de antemano!

**Comment by Demonid** [comment]
Gracias por reportar, la mision ha sido agregada al autocomplete temporalmente
