### ISSUE TITLE
mision de la purificación de Quel'Delar bug

### ISSUE THREAD

**Issue by brandon-castagne** [Demonid/BugTracker#29]
al entregar la espada se me quedo volando y ya no pude hacer nada luego reloguee y me mataron unos elites ahora no tengo la espada como puedo acabar mi mision?
mi id es drakox

**Comment by el-druida** [comment]
abandonando la quest y retomandola en la entrada de Sunwell, no te puede atacar ningun elite a menos que hayas entrado como en grupo. NO ES NECESARIO IR EN GRUPO, solo hablar con el guardia de la puerta junto al que da la quest

**Comment by mestt** [comment]
https://youtu.be/i0KB-rAJER0

aqui tienes un video de como se realiza esta quest.
saludos.

**Comment by rksmw** [comment]
mandame un imbox y te paso al correcion de esta quest

**Comment by OldieButGoldie** [comment]
Dando por respondido el ticket, cierro.
