### ISSUE TITLE
La estadística de bg bug

### ISSUE THREAD

**Issue by alejja** [Demonid/BugTracker#30]
La estadistica de bg anda mal no muestra cuando son alis ni hordas y al matar un ali a otra no da honor y antes no estaba asi

**Comment by el-druida** [comment]
Es el crossfaction, es solo visual, en las tablas de puntajes si ves la faccion real de los jugadores.

**Comment by Demonid** [comment]
Gracias por reportar el fallo, le echaremos un vistazo apenas sea posible
