### ISSUE TITLE
ira

### ISSUE THREAD

**Issue by haicefrog** [Demonid/BugTracker#31]
un gusto saludarte.... quisiera un testeo alos warrior ya que no genera ira como debe 
llevo jugando 5 años con los warrior y no es normal la perdida de ira en segundos y no genera como deve de ser gracias esa es mi inquietud att arios

**Comment by OldieButGoldie** [comment]
> ya que no genera ira como debe

Hola, en qué se basa para llegar a esa conclusión?

**Comment by Demonid** [comment]
Cierro reporte por falta de información valida.
