### ISSUE TITLE
Problemas Con las profesiones

### ISSUE THREAD

**Issue by WichoxX** [Demonid/BugTracker#32]
Buen dia....

Hay un ENORME problema con el tema de las profesiones, mi hermano y yo subimos inscripcion y joyeria respectivamente, pero al momento de llegarlas al maximo, no nos dio items de nivel 80, por ejemplo, al momento de subir inscripcion al lvl 450 da una casilla de seleccion multiple donde se puede seleccionar la clase de la cual se crearan los glifos y en el server no la dio, ademas deberia de haber dado muchos glifos variados desde lvl 70 para arriba, y el mejor glifo que hay es uno de nivel 40... Y con la joyeria el mismo tema, da una casilla de seleccion multiple en donde van los colores de las gemas, y las gemas metas, y en este caso no los dio, tambien da varias gemas de lvl 80 por asi decirlo, y aca no las dan, la mejor gema que tengo en joyeria es una que sale en los filones de titanio, y no puedo crear las gemas que se compran con honor o con emblemas en dalaran, yo se que hay que hacer misiones, y los libros de los escribas para poder sacar los faltante, pero sin embargo el hecho que no de las gemas o los glifos basicos deja mucho que desear, sabemos que estan dando una gran ayuda dejando que las profesiones se suban con x3 de rate pero el no poder crear al final lo que se necesita es un problema aun mayor... saludos.

**Comment by Demonid** [comment]
Buenas, te comento que en principio no veo ningún fallo.

Las recetas de Joyería Épicas, por ejemplo se deben comprar en los vendedores de Dalaran, para ello debes hacer misiones diarias y/o comprar el Token http://es.wowhead.com/currency=61/muestra-de-joyero-de-dalaran con Polvo de Titanio.

Esto lo puedes observar por ejemplo usando el Addon Atlas Loot: 

http://i.imgur.com/BuafjPy.jpg

Que la gran mayoría de recetas épicas de nivel 80 e incluso algunas raras (azules) se deben conseguir de vendedores.

-----------

Por otro lado Inscripción funciona de una manera similar, la mayoría de Glifos tanto mayores como Menores se deben sacar usando el sistema de investigación de inscripción, existe uno para Glifos Mayores y otro para Glifos menores, y ademas existen algunas Glifos que unicamente se pueden aprender usando http://es.wowhead.com/item=45912/libro-sobre-maestria-en-glifos

Aqui te dejo una captura por ejemplo para que veas la forma de conseguir los Glifos:

http://i.imgur.com/n3m1SrI.jpg

Como puedes ver, unos pocos son por Trainer (Entrenador) y la gran mayoría por Investigación y/o por los Libros de Maestría.

Así que como dije anteriormente, nada esta funcionando mal, simplemente debes farmear tus profesiones como siempre ha sido en un server Blizzlike.
