### ISSUE TITLE
Bug Toc (Aullahielo)

### ISSUE THREAD

**Issue by kokito123** [Demonid/BugTracker#33]
**Descripción:**
 Aullahielo al momento de aventarnos hacia la pared para después embestirnos, el buff que solía  darnos    (carrerilla) ya no da,
no se si es un bug o es algo normal espero respondan Gracias
**Que esperas:**
Arreglenlo porfa o respondan  :D
**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
Por favor, sea mas especifico y puntual. Como por ejemplo en que dificultad paso esto? sucedio mas de una vez? faccion? etc

**Comment by Demonid** [comment]
Buenas, te comento que el Buff de Velocidad http://www.wowhead.com/spell=68667, unicamente se da en el modo normal del encuentro, en heroico no lo debería dar.

Podrías dar mas información sobre el supuesto fallo en cuestión? como una captura donde se vea el modo de dificultad y si da o no el Buff.
