### ISSUE TITLE
Bug De Prueba del Campeon de 5 personas 

### ISSUE THREAD

**Issue by XxXEstebanmXxX** [Demonid/BugTracker#35]
**Descripción:**
Esta bug prueba del Campeon de 5 personas pasamos la primera fase y abrimos el primer cofre y de ahi se bugea no pasa a la fase que aparecen los sarcedotes, monjes etc, 
**Que esperas:**
Que lo solucionen lo mas antes posible porque tuve 2 horas queriendo acer y nunca se pudo espero que le den solución lo mas antes posible
**Pasos:**

1. luego de abrir el primer cofre no pasa a la otra fase que hay q matar a los sacerdotes, monjes ,etc

**Comment by el-druida** [comment]
heroico? normal? faccion? hablaron con el anunciador? mas detalles sino es muy generica la descripción

**Comment by XxXEstebanmXxX** [comment]
disculpe de antemano por no dar esos detalles Es en normal y de la Horda. Despues de combatir con los 3 jefes alianzas y abrir el cofre y lotear el anunciador se acerca y nos dice que nos montemos a un huargo osea a las monturas pero ya pasamos esa fase en esa parte se bugea

**Comment by el-druida** [comment]
¿era un grupo completamente horda? Si era normal, no habia ID, intentaron reiniciar la mazmorra? Sucede siempre u ocasionalmente?

**Comment by XxXEstebanmXxX** [comment]
solo fuimos puros hordas en normal no habia ID lo reiniciamos y se bugeaba y siempre pasa de las 6 o 5 pruebas del campeon que hacia apenas 1 pude completar

**Comment by el-druida** [comment]
Ya se ha logrado replicar la falla, se investigara que la causa para luego ser corregida en un corto plazo.
