### ISSUE TITLE
Bug Matanza de Stratholme

### ISSUE THREAD

**Issue by Peludin** [Demonid/BugTracker#36]
En cola a mazmorras aleatorias, me toco a mi en lo personal dos veces La Matanza de Stratholme que ya desde el principio del servidor era de mis preferidas, no existía ningún bug y es mas era una lucha por terminar rápido para conseguir la montura del draco, pero actualmente a sufrido de un sin fin de bugs el primero que yo recuerdo era cuando los ciudadanos pegaban a Arthas al principio y terminaban matandolo antes de que Mal'ganis hiciera su aparición pues bien si solucionaron eso pasa algo similar, al aparecer Mal'ganis se lanza contra Arthas matándolo lo que no deja seguir con la mazmorra, cuando no debería ser así por obvias razones, entonces pido que solucionen ese bug ya que por un lado estamos los que como a mi nos gusta esa mazmorra y también la lucha por el draco, por otro lado también hay personas que al hacer una Diaria heroica les toca esta mazmorra y no tienen de otra que rearmar, dejando a todo el grupo en descanso, Gracias.

**Comment by Demonid** [comment]
Esta mazmorra esta siendo reescrita actualmente, avisaremos cuando se agregue el nuevo script al servidor.
