### ISSUE TITLE
bug de empuñadora 

### ISSUE THREAD

**Issue by psicopata** [Demonid/BugTracker#37]
bbug en la mision  [La purificación de Quel'Delar] no se puede completar 

*no borren  esta  publicacion

**Comment by el-druida** [comment]
Mas detalles sino es muy generica la descripción y de no brindar más detalles se debera cerrar el tema.
facción? abandono y retomo la quest? tomo o no puede tomar el item? etc etc etc Como dije antes, es muy generico su "bug en la mision".

**Comment by el-druida** [comment]
En el anterior ticket le dije lo mismo
https://github.com/Demonid/BugTracker/issues/34

**Comment by el-druida** [comment]
bueno, la probe de mil maneras y siempre me funciono
Consideraciones:
- no es una quest para hacer en "raid", sino solo
- no es necesario estar en "raid" para entrar a la instancia

En el caso que por alguna razon no pueda tomar el item, abandone y retome la quest. Luego reinicie la mazmorra CAMBIANDO LA DIFICULTAD ENTRE 10 Y 25 hasta que vea un mensaje de "la instancia se ha reiniciado". Repita la quest que no es muy complicada por cierto.
