### ISSUE TITLE
bug cadena empuñadura maltrecha

### ISSUE THREAD

**Issue by chevanton** [Demonid/BugTracker#38]
**Descripción:**

**Que esperas:** que reparen el error

**Comment by el-druida** [comment]
@https://github.com/Demonid/BugTracker/issues/37

bueno, la probe de mil maneras y siempre me funciono
Consideraciones:

    no es una quest para hacer en "raid", sino solo
    no es necesario estar en "raid" para entrar a la instancia

En el caso que por alguna razon no pueda tomar el item, abandone y retome la quest. Luego reinicie la mazmorra CAMBIANDO LA DIFICULTAD ENTRE 10 Y 25 hasta que vea un mensaje de "la instancia se ha reiniciado". Repita la quest que no es muy complicada por cierto.

**Comment by el-druida** [comment]
@chevanton si da más información... seria mas util. O al menos lea las consideraciones que escribi antes y luego deje un comentario si le sirvio. Es comun que la gente por costumbre a que esta mision este en modos raros en otros servidores e intenten hacerla por ej. en raid

**Comment by el-druida** [comment]
Por cierto, ¿Cual parte de TODA la cadena? yo asumi que se referia a la ultima parte "purificación de quel'delar pero son 13 misiones en total

**Comment by chevanton** [comment]
Existe un error o almenos no me completa mision al fianl de forja en la mision [templar la hoja] donde tenia que usar el item al final del boss de forja. hice lo requerido y pues se me desaparecio el item y no puedo seguir con la cadena de misiones

**Comment by el-druida** [comment]
Bien, intento abandonar y retomar la quest para rehacerla?? borrar cache  y relogear entre medio de eso.

**Comment by el-druida** [comment]
Acabo de probar ambas quest de "templar la hoja" tanto alianza como horda... Ambas me funcionaron. Revise lo que comente antes sobre borrar cache y rehacer la quest.
