### ISSUE TITLE
bug en el skill  [Golpe mortal]

### ISSUE THREAD

**Issue by psicopata** [Demonid/BugTracker#39]
el golpe mortal solo debe pedir 30 p de ira al parecer aca pide 60p
AREGLEN LA PONTRO

**Comment by Demonid** [comment]
Acabo de revisarlo ingame y funciona correctamente, lo mas probable es que sea un problema visual, prueba borrar cache:

Cierra WoW
Borra la carpeta Cache
Abre el wow y prueba nuevamente.

Dejanos los resultados, en caso seguir con el fallo, intenta aportar una captura de pantalla donde sea te vea con mas de 30 de ira y sin la posibilidad de usar Golpe Mortal.
