### ISSUE TITLE
Bug de Mano de libertad (Paladín)

### ISSUE THREAD

**Issue by frankevin** [Demonid/BugTracker#40]
**Descripción:**
La mano de libertad del paladín se encuentra bugeada y se los presentaré en el siguiente video. No elimina los efectos de ralentización y algunos de ellos pueden ser renovados aún con la mano puesta. También cabe recalcar que la sentencia roja se la puede eliminar al usar el Abalorio de la Horda/Alianza, eliminando su efecto (cosa que no debería pasar puesto que no es un efecto de ralentización ni merme de movimiento.) Les dejo un vídeo de la mano de libertad (olvidé poner el de sentencia pero podrán corroborarlo ustedes mismo al testear lo que les digo).
**Que esperas:**
La mano funcione correctamente y la sentencia de justicia (la roja) sean reparadas
**Pasos:**

1. https://youtu.be/gXOC8BiSNhs
2. 
3.

**Comment by Demonid** [comment]
Buenas, el reporte en principio esta bien hecho, lo que te falto es agregar fuentes o pruebas de que el hechizo debería funcionar como tu dices, seria todo lo que falta para revisar el fallo.

Por cierto, El Debuff Heridas Infectadas siempre se aplicara porque ademas del efecto de ralentización, cuenta con un efecto de reducción de velocidad de ataque.

Quiero pensar que erroneamente agregaste otro bug en el mismo reporte, cada bug debe ser reportado independientemente, sin embargo lo que comentas sobre la Sentencia de Justicia (Roja), es Blizzlike:

Bc icon Patch 2.3.0 (13-Nov-2007): PvP Trinkets: Insignia of the Alliance, Insignia of the Horde, Medallion of the Alliance, and Medallion of the Horde now clear the debuff from Judgement of Justice.

http://wowwiki.wikia.com/wiki/PvP_trinket

Desde el parche 2.3.0 los Trinkets PvP eliminan el Debuff de Setencia de Justicia (Roja) al usarse.

Dicho esto, ambos reportes quedan desmentidos hasta que se presenten mas pruebas.

**Comment by frankevin** [comment]
Considere que en el vídeo muestro también como las cadenas del dk se renuevan cosa que no debería ser así, por ende debería ser así tampoco con la enfermedad que deja el druida pues al hacer inmune a su efecto de ralentización se hace inmune al otro efecto. Es muy molesto que no me pueda limpiar enfermedades (Ej: de Dk escarcha o Sangre sin añublo[Talento]) porque primero se limpian las cadenas. Sucede con todos los poderes que ralentizan, imagine entonces que: Vs un dps (dk, dudu, picaro) y un heler (sobre todo pala o sacer), me disipan la mano de libertad y ya me pueden fácilmente alcanzar porque ya me quedo ralentizado con el efecto anterior.
Espero haberme explicado debidamente, sino es así, lo haré nuevamente de otra forma.

**Comment by Demonid** [comment]
Estas reportando mas Bugs en el mismo reporte, sigues sin mostrar pruebas retail del supuesto funcionamiento que crees es correcto y por ultimo, es indiferente pues el hechizo Limpiar quita veneno, enfermedad y hechizo mágico al mismo tiempo, aun teniendo cadena te quitaras una enfermedad si tienes la suerte de no salir resistido (el DK Frost tiene un talento que reduce 30% la posibilidad de dispel de enfermedades)

Aqui por ejemplo tienes un video de noviembre del 2010 de el oficial mostrando un duelo de un Ret vs Feral, y podras ver que la mano de libertad funciona exactamente igual que aqui:

https://www.youtube.com/watch?v=txtZm3_RkPY

La mano de libertad la puedes ver en el minuto 1:54

Hasta el momento sigo sin ver algún fallo en el funcionamiento actual de la Mano de Libertad.

**Comment by frankevin** [comment]
A partir del minuto 1:17 en adelante, del duelo VS el DK se ve como las cadenas de hielo pueden ser renovadas sin problema alguno por el DK. Cuando la mano del libertad otorga INMUNIDAD a estos efectos y repito, si algo así está activo impide la limpieza instantánea de 1 efecto extra, haciendo gastar más tiempo en limpieza y se pierde DPS.
http://subefotos.com/ver/?502120854443dc7001d1b981f8479a5co.png
énfasis en INMUNIDAD pues es necesario que eso esté activo para mejorar la jugabilidad del paladín. 

http://subefotos.com/ver/?502120854443dc7001d1b981f8479a5co.png

Le dejo además un video donde muestra que en otros servidores como AT (arena tournament) si elimina el efecto inicial y en algunos casos como mago o brujo o dk no se pueden renovar las cadenas.

https://youtu.be/l3S832lAaRM

**Comment by Demonid** [comment]
Parece que sigues sin entender que necesitamos pruebas Retail, no de un server pirata.

Aqui tienes un video de septiembre del 2010 de un Ret vs Frost en el Oficial, podras ver que la mano de libertad no elimina los buffos, simplemente te otorga inmunidad al efecto de ralentizacion:

https://www.youtube.com/watch?v=3tGPkO3JZ3k

Segundo 0:42, veras como tira Freedon y no le quita el debuff de ralentizacion, mas lo hace inmune a los efectos de ralentizacion.

Y este otro vídeo de Julio del 2010

https://www.youtube.com/watch?v=sDmioR4UUGE

Min: 2:10, veras como el Paladin tenia Cadena de Hielo, se tira Freedom y no le elimina el debuff de cadena de hielo.

Y vuelvo a repetir, necesito pruebas retail, osea del oficial, no de un servidor pirata.
