### ISSUE TITLE
Bug de Traslación mago

### ISSUE THREAD

**Issue by frankevin** [Demonid/BugTracker#41]
**Descripción:**
La traslación del mago suele no funcionar correctamente apenas encuentra un minúsculo obstáculo lo cual no debería ser así, solamente cuando encuentra obstáculos grandes no funciona, pero cuando son así de minúsculos deben ser ignorados y funcionar correctamente. Además que no traslada los 20 metros en algunos casos como se muestra en el video.
**Que esperas:**
Se solucione debidamente la traslación en todas sus aplicaciones (Bg's, arenas, zonas de duelo, etc.)
**Pasos:**
1. https://youtu.be/ZAR8PWiVjUQ

**Comment by Demonid** [comment]
Confirmado, gracias por reportar, intentaremos solucionarlo apenas nos sea posible

**Comment by Demonid** [comment]
Solucionado, gracias por reportar.
