### ISSUE TITLE
Bug misión " ´NECESITARAS UN OSO" de la cadena Hijos de Hodir

### ISSUE THREAD

**Issue by yesamy** [Demonid/BugTracker#42]
podrías revisar esto urgente porfavor
Pasos:
PJ Paladin : Warhammerdj

1. El NPC me da la mision nesesitaras un oso autocompletada
2. voy a entregarla y  desaparecen el NPC donde debo entregar la misión 

https://youtu.be/2JlcBYzqpK4

**Comment by el-druida** [comment]
Bien, estuve revisando y la mision no esta bug como supone usted. Es un tema de fases posiblemente causado por usted al abandonar y retomar misiones previas. Seria necesario verle online para revisar el personaje.
