### ISSUE TITLE
La clave de condenación: La carga de Ar'tor (Misión bug)

### ISSUE THREAD

**Issue by godlike93** [Demonid/BugTracker#44]
**Descripción:**
Se supone que debe estar un demonio parecido a un pulpo, pero no está y nunca aparece; además, se supone que si el espíritu acompañante hace daño a algún bicho, este no debería dar loot, pero sí da loot. 
**Que esperas:**
Aquí dejo un video de la misión como debería ser:
https://www.youtube.com/watch?v=U414tWob4P8
**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
La misión esta funcional, acabo de probarla dentro del juego. El "pulpo" no aparece por si solo sino que usted debe buscarlo hasta que el espiritu que lo acompaña lo hace aparecer.

https://i.gyazo.com/8d6f715955af7da19b17aca3875dc15f.jpg

**Comment by godlike93** [comment]
Pues sí, la acabo de hacer, pero créeme que he dado vueltas y vueltas por todo ese territorio con el fantasma durante mucho tiempo y no apareció. Abandonaba y retomaba la quest y reactivaba al fantasma y nada. Quizás es suerte o no sé, pero no soy el único al que tenia este problema. Igual gracias por tu imagen ya que estuve yendo a ese lugar a cada rato hasta que apareció.

**Comment by el-druida** [comment]
Son varios lugares puntuales donde puede aparecer pero tiene CD su invocacion. Además quien hace la invocacion es el espiritu que te sigue.

**Comment by godlike93** [comment]
Pues ya estoy en la parte final, pero no puedo atacar al elite; hace media hora que se manda su texto y ya repetido, pero no lo puedo atacar. Es eso normal o que?
![wowscrnshot_052817_233843](https://cloud.githubusercontent.com/assets/28567680/26536658/e44a0c12-43fe-11e7-9aff-5c8bcac24a91.jpg)

**Comment by godlike93** [comment]
No pues ya está, con solo esperar ahí no pasa nada. Hay que hablar con un orco que está más atrás y ya. Todo listo

**Comment by el-druida** [comment]
pues... hay que tener paciencia, es una mision, tienen sus dialogos etc etc. No siempre es salir dando golpes.
