### ISSUE TITLE
La clave de la condenacion, la carga de Borak

### ISSUE THREAD

**Issue by erkiv** [Demonid/BugTracker#45]
**Descripción:**
segun la mision, debo emboscar y matar a Ruul el ensombrecedor y despojar el tercer trozo de la clave de la condenacion, pero ya recorri todo el campo ala abisal durante mas de 1 hora, incluso con otro pj he hecho la cadena de misiones y tampoco, se queda en la misma parte, Ruul no aparece
**Que esperas:**
que aparesca Ruul, matarlo y despojarle la tercera parte de la clave de condenacion, segun los videos y tutoriales es llegar al campo ala abisal y el tal Ruul aparece.
Gracias por la atencion prestada.
**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
El npc no es estatico, se mueve todo el tiempo. Ire a revisar y pondre una imagen.

**Comment by el-druida** [comment]
https://gyazo.com/034777b30c1e6c223dc4b4a8ebfb921d

El npc esta... hay que buscarlo nada más
