### ISSUE TITLE
Posible bug en cadena de misiones de empuñadura maltrecha

### ISSUE THREAD

**Issue by Trocador** [Demonid/BugTracker#47]
**Descripción:**
Bueno lo que sucede es que estaba haciendo la cadena de misiones que te da la empuñadura maltrecha, en consistencia la mision: http://es.wowhead.com/quest=24560/templar-la-hoja , lo que sucede es que cuando llego al ultimo boss de la forja de almas, lugar donde se completa la mision, y apreto el item que te dan para terminarla, http://es.wowhead.com/item=49739/queldelar-reforjada#screenshots (este objeto), se activa y castea, todo normal, lo que sucede es que luego de hacer eso el objeto desaparece, de mi inventario, y encima la quest no se completa.
Quisiera que se me devuelva el objeto o la empuñadura maltrecha, por que es un raro item que no sale a menudo. Si se necesita pruebas o algo, avisenme y me contacto sin  ningun tipo de problema
**Que esperas:**
Que cuando no se encuentra en el crisol de almas el objeto no se pueda activar
**Pasos:**

1. Activar el objeto http://es.wowhead.com/item=49739/queldelar-reforjada#screenshots en cualquier parte de la zona del ultimo boss de forja de almas (claro obviamente teniendo la mision para que se compruebe que no se completa la quest)

**Comment by el-druida** [comment]
abandono y retomo la quest para rehacerla?? borrar cache y relogear entre medio de eso.
Por que no logro reproducir ese error, siempre luego de lanzar el item obtengo la siguiente. Fijese si no tiene lleno el inventario o similar.

**Comment by Trocador** [comment]
muchas gracias solucionado
