### ISSUE TITLE
No Cumple una Mision de la Empuñadura Maltrecha

### ISSUE THREAD

**Issue by Hilaridiego** [Demonid/BugTracker#48]
**Descripción:**
Hola , mi personaje Daynus chaman, empezo la mision del empuñadura, y la segunda quest de mi mision , (Lo que saben los dragones) no quiere cumplirse, solo te pide que hables con un npc que se encuentra en el Templo del reposo del Dragon, y pues no se cumple nada.
**Que esperas:**
Bueno tendria que hablarse al Npc  Krasus Templo del reposo del Dragon y mandarme despues a  hablarle al Npc Tybalin en el Enclave de Plata, en Dalaran , solamente a si se cumple la mision.  
Por favor MJ Arregla mi mision de mi personaje Daynus Alianza , espero que no ocurra con otros Pj del servidor, espero su solucion lo mas antes posible , Por Favor . Se lo ruego.
**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
Abandonaste y probaste de nuevo la mision? inventario lleno? relogeaste? no tenes el registro de misiones lleno? Revisa todo eso antes y luego comenta un poco mas en profundidad
