### ISSUE TITLE
bug mision quel'danas Thalorien Buscalba

### ISSUE THREAD

**Issue by Trocador** [Demonid/BugTracker#49]
**Descripción:**
Sucede que estaba completando cadena de misiones de la empuñadura maltrecha y pasa que en la mision http://es.wowhead.com/quest=24535/thalorien-buscalba entro todo normal y estoy completando cuando me matan D: (es q soy un mago y no aguanto nada) renazco y Thalorien se murio por que no lo ayude, reconecto para volver a hablarle, cuando vuelvo ya no puedo hablar a los restos de Thalorien, crei que se solucionaria con abandonar la mision pero voy a recoger de nuevo y ya no puedo D: , tengo pruebas que ya complete las misiones ya que tengo otra empuñadura maltrecha y al querer coger mision me dice mision completada, quisiera que me dieran una solucion por favor.
**Que esperas:**
que la mision fallida se hiciera correctamente(Si es que fallas, que correctamente puedas reiniciar la mision sin necesidad de reconectar ni nada)
**Pasos:**

1. fallar la mision (muriendo o dejando que muera el espiritu al que debes ayudar)
2. intentar hablar de nuevo con los restos

**Comment by el-druida** [comment]
Cuando se muere haciendola, debes esperar unos minutos a que revivan los npc's. Abandona la quest, tomala nuevamente y volve con los restos.

**Comment by Trocador** [comment]
muchas gracias siempre me estas ayudando men solucionado !!
