### ISSUE TITLE
[Bug] Spirit Walk - Chamanes - Hace inmune a roots/snares al chamán por algunos segundos

### ISSUE THREAD

**Issue by Zlorak** [Demonid/BugTracker#5]
El spell de los chamanes mejora/enhancement que proviene de sus lobos invocados llamado Spirit Walk/Camino de Espíritu **[IDSpell= 58875]** quita los snares/roots y TAMBIÉN vuelve al chamán inmune a estos durante un periodo apróximado de 1s - 2s lo cual no debería pasar ya que sólo debería quitar los roots/snares que el chamán tiene al momento de lanzar el hechizo y dejarlo vulnerable a cualquier otro que se le aplique después de lanzarlo. 

Link Spirit Walk en Twinhead:
https://wotlk-twinhead.twinstar.cz/?spell=58875

**Comment by Tehno123** [comment]
tengo un problema con mi dk cuando uso  [Levantar a muerto] no sale el muertito ya olvide talentos y los puse otra vez pero no funciono

**Comment by OldieButGoldie** [comment]
> tengo un problema con mi dk cuando uso [Levantar a muerto] no sale el muertito ya olvide talentos y los puse otra vez pero no funciono

Hola, por favor cree un reporte nuevo, no use los reportes de otro jugador, mantengamos el tracker limpio.

Un saludo

**Comment by OldieButGoldie** [comment]
@Zlorak, el spell de inmunidad es el siguiente: https://wotlk-twinhead.twinstar.cz/?spell=58876, por lo que puede observar otorga inmunidad por 4 segundos.

Queda pendiente revisar si se trata de un buff único para los lobos o el chamán debe heredarlo también

**Comment by OldieButGoldie** [comment]
Hola, luego de efectuar las pruebas y revisar la información disponible para el parche, llego a la conclusión que la inmunidad es un efecto secundario blizzlike, aplicando tanto a los lobos como al chamán:

http://www.wowhead.com/spell=58875/spirit-walk#comments:id=637150
