### ISSUE TITLE
BUG en mision TEMPLAR LA HOJA cadena de mision de empuñadura

### ISSUE THREAD

**Issue by rogger424a** [Demonid/BugTracker#50]
Descripción: 
Bug en la mision de empuñadura TEMPLAR LA HOJA
      Que esperas:
 Matamos al jefe Devora Almas y despues a momento de imbuir la empuñadura este no bota arreglen ese bug me quede sin empuladura ando mas de 2 horas esperando ayuda y no saliendo de la instancia para demostrar el bug y mi mision Quiero mi empuñadura templada para seguir con la cadena de misiones .... att: pj Ifnit

**Comment by el-druida** [comment]
Con abandonar la quabandono y retomo la quest para rehacerla?? borrar cache y relogear entre medio de eso. Por que no logro reproducir ese error, siempre luego de lanzar el item obtengo la siguiente. Fijese si no tiene lleno el inventario o algo similar. Como toda mision si algo falla por alguna razón antes de considerar "bug" se debe reintentar.
Con una descripcion tan superflua es imposible reproducir la falla. ¿Faccion? ¿Era un grupo de facciones mixtas? ¿Normal o hero? ¿era el unico para realizar la quest o habia otro mas? ¿Cuantas veces le ha sucedido?

**Comment by el-druida** [comment]
Si ya tiene la instancia limpiada, como dije, abandone y retome la quest para confirmar falla. En mi caso sea con un pj alianza u horda no logro reproducirla.

**Comment by rogger424a** [comment]
es la primera vez que me sucede mi pj es horda y en la party estabamos 4 h y un ali ademas cuando tire la empuñadura no me la devolvio niu aparecio el item Lo hicimos en forja normal ahora me d miedo abandonar la mision es la unica pruebaa que tengo que estoy en la mision

**Comment by rogger424a** [comment]
jeje lo volvi a hacer se me desbugeo jeje muchas gracias -.- creo que soy un poco manco xD

**Comment by el-druida** [comment]
Es obvio que no se devuelve el item luego de arrojado, es un consumible. En todas las misiones que se otorga un item para ser usado, cuando se abandona y retoma la misma, se vuelve a recibir el item.
