### ISSUE TITLE
empuñadora bug

### ISSUE THREAD

**Issue by psicopata** [Demonid/BugTracker#51]
[Las Cámaras de Reflexión] 

al parecer la espada nose presenta y no deja completar la mision
areglenlo cuanto antes

**Comment by el-druida** [comment]
La mision funciona, abandonala, retomala y volve a entrar a la instancia nuevamente luego de haberla reiniciado.

**Comment by psicopata** [comment]
deme un momento are esos pasos

**Comment by el-druida** [comment]
Y por favor para la proxima vez incluya mas detalles como ID de la mision, estaba en grupo o solo? normal o hero? faccion ?? etc
Con una descripcion tan superflua complica ubicar la falla en el caso que exista alguna.
