### ISSUE TITLE
Chat glbal bug

### ISSUE THREAD

**Issue by Pudredumbre** [Demonid/BugTracker#52]
**Descripción:**
No puedo ni clickear ni /join buscargrupo ni hablar de ninguna forma, aunque si puedo leer los mensajes que dicen  susurrar a quienes hablan, le pasa lo mismo a mi hermano.
**Que esperas:**
Un poco de ayuda porfavor :)

**Comment by el-druida** [comment]
¿Ya probo, deslogear luego borrar cache. Ingresar al juego y "reestablecer" las opciones de chat?
O sea, da click derecho en la pestaña "general" luego va a la opcion configuracion. En la ventana que se abre busque el boton "Reestablecer chat" y darle click.

**Comment by Pudredumbre** [comment]
Así es, ya lo he intentado y no funciona

**Comment by el-druida** [comment]
Reestablezca la carpeta WTF y logee sin addon. El chat en si no tiene problemas, ya probe en 5 casos que el resetear la configuracion del programa cliente (su propio wow) devuelve la funcionalidad.

**Comment by Pudredumbre** [comment]
Borré el contenido de WTF. borré el contenido de Caché, inicié sin addOns, di /join buscargrupo, di reestablecer ventanas de chat, la verdad no sé qué más puedo hacer. es sólo con /4. Buscargrupo... de resto puedo hablar normal (pasa exactamente lo mismo con la cuenta de mi hermano, en ambos pc, desde ayer), gracias por la colaboración.

**Comment by el-druida** [comment]
Vuelve a borrar cache y luego logear. Abandona el canal y luego vuelve a unirte. Segun describiste antes, te uniste pero nunca lo abandonaste. Es un error recursivo en ocasiones.

**Comment by Pudredumbre** [comment]
Ya se ha arreglado el problema, muchas gracias!.
