### ISSUE TITLE
Bug en uso de los abalorios de faccion alianza( Prueba del Cruzado) en raid de icc "Horda"

### ISSUE THREAD

**Issue by yesamy** [Demonid/BugTracker#53]
Bueno paso a explicar que no puedo usar items como abalorios ni otro equipo que sea exclusivamente alianza en icc "Horda" 
por ejemplo
item t9 cual  por ejempo en el paladin alianza se llama  [Yelmo de conquista de Turalyon] y en el caso de la horda el mismo item t9 paladin  [Yelmo de conquista de Liadrin]

pues aqui les pongo un video donde no puedo usar el  [Escarabajo trabador de Satrina] alianza en la ICC HORDA

https://www.youtube.com/watch?v=AeaXs4oU2Xc&feature=youtu.be

**Comment by el-druida** [comment]
¿Y sin mezclar las facciones en la raid, puede usarlo?

**Comment by Demonid** [comment]
El fallo esta en que al cambiar de facción durante la raid, no te permite activar Buffs de un item que es para la alianza.
