### ISSUE TITLE
Cambie de contraseña y Ahora no entra mi cuenta 

### ISSUE THREAD

**Issue by mikemikejack** [Demonid/BugTracker#54]
**Descripción:**
Cambie de contraseña y Ahora no entra mi cuenta en el juego. EN la pagina web si logeo normal. pero en el juego no.
**Que esperas:**
Poder entrar a mi cuenta y jugar. 
**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
@Demonid

**Comment by Demonid** [comment]
@mikemikejack 

Dejame los siguientes datos:

Nombre de algun personaje:
Ultima conexion:
Pais:
Correo electronico vinculado a la cuenta:
Numero de personaje:

**Comment by mikemikejack** [comment]
Patriarca - orco, cazador nivel 80
Ultima conexión: ayer aproximadamente entre las 8 y 9 de la noche. Hora
Local (Lima-Perú)
Pais: Perú
Correo Electronico: Migueljimenezcarrasco@gmail.com
Numero de personaje: 80 es el ultimo pj creado en mi lista de esa cuenta.
Tambien tengo un Dk - orco , Pichula, y otros lows como jackjack,
jackblack( paladin elfo de sangre lvl 80 )

2017-06-10 0:47 GMT-05:00 Demonid <notifications@github.com>:

**Comment by Demonid** [comment]
@mikemikejack La contraseña ha sido cambiada a 123456, prueba entrar e intenta cambiar la contraseña apenas te sea posible.

**Comment by mikemikejack** [comment]
Muchas gracias, ya puedo entrar. solucionaron mi problema bastante rápido
amigos, muchas gracias.

2017-06-10 7:57 GMT-05:00 Demonid <notifications@github.com>:
