### ISSUE TITLE
posible bug  especializacion de alquimia

### ISSUE THREAD

**Issue by Trocador** [Demonid/BugTracker#55]
**Descripción:**
Tome la mision http://es.wowhead.com/quest=10906/maestro-en-elixires pero no la complete y me puse en forma para tomar en cambio: http://es.wowhead.com/quest=10907/maestro-de-transmutacion lo que sucede es que voy a tomar la mision que me dicen da de este npc http://es.wowhead.com/npc=16588 
pero no me da ninguna otra mision como daba antes.
ademas que no puedo ir a tomar de http://es.wowhead.com/npc=22427 ya que no le encuentro
no se si sera un bug osi estoy haciendo algo mal por favor disculpan mi ignorancia sobre el tema de alquimia es primera vez que la subo
**Que esperas:**
ayuda sobre el tema
**Pasos:**
1. tomar mision  para maestro de elixires
2. abandonarla
3. intentar tomar mision para maestro de transmutaciones

**Comment by el-druida** [comment]
BIen, tenes dos opciones... ir con el npc 22427 o subir la especializacion q tengas a mano y luego con el libro for dummies (en una choza de un gnomo en tanaris) olvidarla y aprender ahi mismo otra.
Por cierto el npc 22427 esta donde indica Wowhead, seguramente lo has cruzado de largo.

**Comment by Trocador** [comment]
le encontre pero no me da ninguna mision que hago?

**Comment by el-druida** [comment]
Cual es su nick en el juego?

**Comment by el-druida** [comment]
tratado in game
