### ISSUE TITLE
Bug mision "necesitaras un oso"

### ISSUE THREAD

**Issue by erkiv** [Demonid/BugTracker#56]
**Descripción:**
mision "necesitaras un oso" el npc estando a 3 - 5 metros desaparece
**Que esperas:**

que el npc no desaparezca y continuar mi camino a la obtención del parche de esta faccion

**Pasos:**

Saludos, decidido a obtener los parches que dan esta facción para pve, me dispuse a hacer la cadena de misiones, que empieza farmeando una piedra de unos gigantes que inicia una misión, este me manda donde torin y completada me da 22000 de repu, torin me manda hablar con el rey de los hodir, pero me ataca por que según reputación estoy en guerra (no le puedo quitar el chek), soy odiado y son 36000 - 22000 de la mision aun hay 14000.
Debido a esto empece la cadena de misiones del vylkur (o algo asi, empieza rescatando a 5 globin de las jaulas), pero como en el anterior Issues que ya existe, el npc desaparece, (como en el video del Issues anterior) la cadena de misiones la hice continua, no abandone ni recupere ninguna mision, y todo lo hice en una misma conexion.
1. 
2. 
3.

**Comment by el-druida** [comment]
debes tener un item de una mision de thorim me parece... que te fasea en esa zona. No hay bug en si sobre las misiones o eventos.

**Comment by erkiv** [comment]
ehmmm, creo que una cadena de misiones es cuando las misiones se encadenan una tras otra, y como aclare, inicie la cadena de misiones toda de una vez, sin desconectarme ni nada, sin abandonar la misión o algo que se le parezca, y si sirve de algo dejo aquí la guía de la cadena de misiones que uso:
http://eu.wowrean.es/wow/es/foro/temas/vertema.php?id=1713
gracias por la atención prestada.

**Comment by el-druida** [comment]
No estoy hablando de la cadena con las amazonas, revise su inventario porque es probable lo un item que le haya faseado. Con solo tenerlo ya se produce el faseo, se haya completado, abandonado o nunca hecho la mision. Solo tenerlo. No recuerdo el ID del item en cuestion pero lo mismo sucedio con otro jugador hace unos dias.

**Comment by el-druida** [comment]
Por casualidad no tendra activa alguna mision de las diarias de toc?

**Comment by erkiv** [comment]
saludos, efectivamente soy muy pve y lo mio es subir repu con las facciones y demás, para obtener monturas parches, etc.
estoy haciendo diarias del torneo argenta esas que dan un emblema azul como un caballito de mar, ahora mismo estoy reuniendo 15 que me pide una misión, no se si a estas se refiere. si es necesario puedo listar las misiones que tengo por hacer.

**Comment by el-druida** [comment]
Algunas de las misiones diarias de TOC te fasean, abandonelas y chequee si continua con la cadena de las vrykul

**Comment by erkiv** [comment]
ya pude continuar con la cadena de misiones, tenia cojida la misión "forjando una alianza", que es de las finales, fue dejar esa misión y ya el npc no desaparece.

**Comment by el-druida** [comment]
Gracias por colaborar, pude constatar que lo que inicia el tomar esa quest "forjando una alianza" es la causante del mal faseo que no deberia estar disponible hasta que no se termine la cadena vrykul. Ya se ha hecho la correccion para que a futuros jugadores no les suceda lo mismo.
