### ISSUE TITLE
No me aparece el icono del personaje que esta en mi grupo de banda

### ISSUE THREAD

**Issue by Wietar789** [Demonid/BugTracker#57]
**Descripción:**
cuando estoy en grupo puedo ver el icono del personaje pero en banda ya no y tambien por cumbres tormentosas no puedo ver a los hordas o alis en cierta zona
**Que esperas:**
espero que solucionen esto porque en esa zona esta skoll y quiero domesticarlo
**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
A ver a ver vamos por partes... en grupo o banda? son cosas diferentes. Fijese en las opciones de interfase sino tiene activa la opcion "ocultar retrato".
Sobre los de la zona de cumbres, verifique que no tenga activa alguna quest como la #12924 "Forjando una alianza" o alguna diaria de TOC.

**Comment by Wietar789** [comment]
lo de la banda se soluciono pero lo de cumbres no por la zona de skoll veo gigantes de hierros en vez de dragones como la mayoria

**Comment by el-druida** [comment]
Le sugiero entonces que termine las quest que haya empezado en la zona. Si es eso, no es bug ni falla sino de su parte falta de completar alguna cadena de quest qe ha dejado por la mitad

**Comment by el-druida** [comment]
Para ser exacto la cadena de rescatar a Brann Barbabronze
