### ISSUE TITLE
Daño Blanco de Halion SR Bug

### ISSUE THREAD

**Issue by Flechero** [Demonid/BugTracker#58]
**Descripción:**
 Buenas estuve en raids de halion , como no soy tanque no tengo prueba de cuanto pega el boss pero he notado que pega demasiado poco , cuando muere el tanque y me pega el boss no me baja ni 10k para ser un boss que es a la par de LK de fuerte, y con mi experiencia en otros servidores halion no es tan fácil de tirar porque hay veces en que se les muere el tanque  pero en este caso al tank no lo bajaba ni del 50% para tener 5k de gs  nada mas , en cuanto LK pega 25k en blancos.

**Que esperas:**
 Espero que que se arregle pronto puesto que no es nada divertido y entretenido tumbar un boss como halion tan fácil de 25 aparte como digo casi todos  tienen 5k  de gs y eso hasta en otros servidores como lo es el rean  muchos con mas gs se ha wipeado.

**Pasos:**
1. Dejarse pegar por Halion para comprender que pega demasiado poco.

**Comment by Demonid** [comment]
Tras el siguiente reinicio el Daño Blanco de Halion sera modificado con valores mas Blizzlike, muchas gracias por reportar.
