### ISSUE TITLE
bug de ingeneria

### ISSUE THREAD

**Issue by psicopata** [Demonid/BugTracker#59]
![lol](https://user-images.githubusercontent.com/28879392/27263790-7dd2b6bc-5436-11e7-9576-aae1b6c2f1cf.png)

 puedo usar mis guantes de ingeneria  ni por mas que borro cache  ,salga de banda ,esto solo pasa en icc 
AREGLENLO

![lol](https://user-images.githubusercontent.com/28879392/27263790-7dd2b6bc-5436-11e7-9576-aae1b6c2f1cf.png)

**Comment by el-druida** [comment]
Se agradeceria algo mas de información como que mensaje recibe, una imagen o al menos una descripcion mas detallada. Y no tanto un lenguaje imperativo.

**Comment by psicopata** [comment]
NO ENCUENTRO LA OPCION DE PÁRA MANDAR IMAGEN

**Comment by psicopata** [comment]
AI ESTA  ME DICE NUNCA PODRE EQUIPAR ESO NO SE QUE ASE REFIER SI YA LO TENGO EQUIPADO

**Comment by Demonid** [comment]
Este fallo esta relacionado con: https://github.com/Demonid/BugTracker/issues/53
