### ISSUE TITLE
Bug Shaman/Hunter/Rogue/Fear/Dk

### ISSUE THREAD

**Issue by Cruelity** [Demonid/BugTracker#6]
Lo que vi recientemente mientras areneaba:
Shaman.
1. Tras ser desarmado el chaman el uso de poner totems es inutilizable.
2. En mejora el uso de los lobos al estar ellos columneando, el buffo de sprint no se le otorga al shaman.
3. El uso de los totems base cd esta mal configurado Ej. Al poner en medio del fear este deberia ser limpiado instantaneamente al igual que el Totem nexo con el slow.
Hunter.
1. Hay un ligero bug con las pets de hunter (y sham) el cual estar tras una columna no bonifica al Cazador(Buffos activables de pet).
2. El hunter tras lanzar salva hay una posibilidad de entrar en estado de Stopcasting (Inmovilizado y sin poder lanzar la habilidad)
Bonus: Las pets al estar en una plataforma elevada quedan bugueadas y no bajan hasta que esten en pasivo. 
Rogue.
1. La capa de las sombras suele no quitar los hechizos, ni resistirlos
2. El buff del esfumarse esta bug (Proximo a explicar con video)
3. Estando en sigilo con un Spell de absorción puesto cualquier daño AoE lo revela
Priest/Lock
1. Te envia a un lugar inexacto visualmente a quien esta bajo el efecto del Fear
Dk
1. La atracción letal no deberia ser usable a rango melee

**Comment by Demonid** [comment]
Lo correcto es que coloques cada reporte individual para poder revisarlo bien, si puedes dejar una captura o procedimiento mejor, de otra manera cerraremos el tema al reparar uno u otro bug y los demas se perderan.
