### ISSUE TITLE
TALENTO BUG

### ISSUE THREAD

**Issue by LynxWyvern** [Demonid/BugTracker#60]
**Descripción:**
El talento de druida rama de restauración, Maestro en cambio de formas debería dar un 4% de daño físico en forma de oso de daño físico y no lo hace, al igual que un 4% aumento de crítico en forma felina tampoco lo hace, no sé si en las demas especies cumpla lo que dice ese talento, solo soy over melee dps.

**Comment by el-druida** [comment]
No encuentro ninguna falla en el talento en el servidor de desarrollo
Sin talento "Maestro cambio de formas"
Daño base 200
https://gyazo.com/e09b90573e052ba6ce91b3f41c47c199

Con talento "maestro cambio de formas"
Daño base 220 + 4% de ese daño base 
1% = 2
4% = 8
Daño total 208
https://gyazo.com/25621afe98633c4c7dc9215972edf120

En todo caso, resetee sus talentos y siempre que ponga talentos recuerde romper transformacion y volver a hacerla para que se actualicen los valores.

**Comment by Demonid** [comment]
Despues de realizar varias pruebas queda confirmado que el talento que reportas funciona correctamente.
