### ISSUE TITLE
Bug baile ardiente en el poste caliente

### ISSUE THREAD

**Issue by crackcocaine** [Demonid/BugTracker#61]
Pz el logro baile caliente ardiente en el poste caliente esta bug me pongo todo el set del festival y giro en el poste y nada que me salta el logro lo intente de todas las formas posibles por una hora y aun asi no me salto el logrito

**Que esperas:**
Que me ayuden o lo reparen por que ya que no hay mucha actividad en el server al menos uno mata el tiempo haciendo este tipos de eventitos  

https://www.youtube.com/watch?v=yTmQMg9_l38

**Comment by el-druida** [comment]
Mmm raro, deberia estar funcionando. Le dare una mirada. Por cierto "Malabarista" y "cazar antorchas" estan arregladas en desarrollo ya pero no se si ya se aplicaron el servidor, le aviso antes que realice un post por las dudas.

**Comment by Trocador** [comment]
si ta arreglado malabarista y cazar antorchas, me salto el logro
 en cuanto al del baile yo tengo el mismo problema una solucion pls D:

**Comment by Shotelf** [comment]
Igualmente estoy tras el logro para salir de la rutina del pve y pvp y ya me di cuenta que arreglaron "Malabarista" y "Cazar Antorchas" lo único que si esta pendiente es el tema del baile en el poste, igual lo intente con todas las guías y formas posibles pero no salta el logro, gracias por la atención prestada.

**Comment by el-druida** [comment]
Ya se encuentra funcional en desarrollo, luego sera aplicado en el servidor live.
