### ISSUE TITLE
hit problem

### ISSUE THREAD

**Issue by taurensoul** [Demonid/BugTracker#62]
Creo que el hit de mi dk esta funcionando mal, nada mas que agregar.
https://prnt.sc/fnb5ua
https://prnt.sc/fnb586

**Comment by Demonid** [comment]
Para empezar no estas especificando si hablas de auto ataques o habilidades, para capear habilidades basta con 8%.

Ahora para capear los auto ataques, en una clase con Dual Wielding (Dos armas) necesitas los siguientes caps:

v. Level 80 mob: 5.0% / dual-wield: 24%
v. Level 81 mob: 5.5% / dual-wield: 24.5%
v. Level 82 mob: 6.0% / dual-wield: 25% (level of most heroic bosses)
v. Level 83 mob: 8.0% / dual-wield: 27% (level of raid bosses) 

27% contra un objetivo nivel 83, que es el nivel que tienen los bosses en ToC, ICC, Halion etc.

Fuente: http://wowwiki.wikia.com/wiki/Hit

En resumen, no tienes suficiente indice de golpe para evitar fallar auto ataques, y no es recomendable capearlo tampoco.
