### ISSUE TITLE
Duda sobre Item y Mision Receta encharcada

### ISSUE THREAD

**Issue by Crok2765** [Demonid/BugTracker#63]
**Descripción:**Duda sobre Item [Receta encharcada](http://es.wowhead.com/item=48681/receta-encharcada) y Misión [Receta encharcada](http://es.wowhead.com/quest=14203/receta-encharcada) se puede volver hacer como si fuera el [Collar dañado](http://es.wowhead.com/item=43297/collar-danado) para sacar premios de cocina ya que eh estado checando en varios foros y en wowhead que si es posible pero aqui en el server no deja sale el mensaje que ya eh a completado la misión
**Que esperas:**
Si lo pudieran checar ya que el GM Dorian me dijo que estaban bien a lo blizz pero si lo estoy checando desde wowhead y dice que es repetible... entonces que
**Pasos:**

1. Al tomar la mision del Item [Receta encharcada](http://es.wowhead.com/item=48681/receta-encharcada) la debes de entregar a Christi Stockton en la Ciudad de Dalaran.
2. Si Vuelve a salir dicho item puedes volver hacer dicha misión

**Comment by el-druida** [comment]
Describeme mejor la situacion... encontraste el item que la inicia, tomaste la quest, entregaste. Y luego volviste a encontrar de nuevo el mismo item? Por cierto, tenes mas las ID's, el item que la inicia es el 48679 y no el 48681. Este ultimo es el que te da la quest cuando se acepta.
Acabo de probar agregarme 5 veces el item, activar y entregar 5 veces la quest. Nunca un problema...

https://gyazo.com/396e7ae5a46cb835418fac0b5b01b710

Por lo tanto llego a la conclusión que la mision es repetible sin ningun problema. Y es algo desde su lado, no se quizas el Quest Log lleno??

**Comment by el-druida** [comment]
debido a que el jugador no se ha vuelto a presentar... cierro
