### ISSUE TITLE
Bug Diablillo brujo

### ISSUE THREAD

**Issue by erkiv** [Demonid/BugTracker#64]
**Descripción:**
Saludos, no se si es un bug o es propio del parche, pero desde mas o menos se implemento ICC, el diablillo tiene un problema en su habilidad "Descarga de fuego", uno activa descarga de fuego del diablillo, pero al montar (sea cual sea la montura) y posteriormente descabalgar, esta habilidad del diablillo esta deshabilitada, es decir uno tiene que volver a darle click en su hechizo, esto en mazmorras le viene fatal al brujo, por ejem: en foso me la pase con el diablillo solo dando golpes, al no percatarme de este digamos bug, no se si es solo a mi, ya probe quitando todos los Addons, restaurando valores por defectos de la interfaz, borrando carpetas, cache y Wtf
**Que esperas:**
como dije antes del parche ICC no estaba pendiente de si el hechizo se deshabilitaba o no y espero volver a lo normal.
**Pasos:**

1. habilitar descarga de fuego de diablillo
2. montar
3. desmontar, descarga de fuego de diablillo esta deshabilitado
Gracias por la atención prestada.

**Comment by Demonid** [comment]
Este fallo es genérico, pasa con todas las pets, @arks-dev
