### ISSUE TITLE
perdida de items urgente nito para ayudar ami guild

### ISSUE THREAD

**Issue by haicefrog** [Demonid/BugTracker#65]
el dia de hoy 24 de este mes logeo y me quiero ponerme de tanque me encuentro que se han perdido mis items porfabor ayudenme en esa cuestion no e tomado fotos ni nada son items de tanque porfabor gracias

**Comment by Demonid** [comment]
Podrias dejar mas datos? como el nombre de tu personaje? que items se perdieron? cuantas personas tienen acceso a tu cuenta, etc.

**Comment by haicefrog** [comment]
gracias demonid me perdio el abalorio de tanque de toc la espada de tyranus el el pecho que es con el trofeo de toc mas casco  la capa de tanque de camaras de reflexion mas el escudo el nombre de mi warrior se llama arios y solo yo tengo axeso  a mi cuenta gracias demonid

**Comment by Demonid** [comment]
El dia 23 tenias todo sin problema no?

**Comment by haicefrog** [comment]
chuta demonid me parece que si como no me respondias entonces no recuerdo bien pero creo que si 
en cuestion es mira que ami nomas no se me perdio a algunos se les esta desapareciendo cosas tienes que arreglar ese problema ... els erver esta bueno y eso pero sisige asi como dicen la gente se ban a ir ... porque es tiempo que pierden osea sacan un iten para que se les pierda de una osea eso les desobliga ..... tienes que solucionar ese problema demonid es por el bien del server .. y obbio por el bien tuyo
