### ISSUE TITLE
Dps del caza bug ( quimera )

### ISSUE THREAD

**Issue by Flechero** [Demonid/BugTracker#66]
**Descripción:**
Buenas justo estaba probando en los muñecos el dps del caza y me he dado cuenta que tiene bug el quimera hice 2 intentos por 1 minuto sin buffos y sin nada , solo con el equipo a ver cuanto pegaba. Todo comenzó cuando estaba probando diferentes rotaciones y me doy cuenta de que el puntería esta pegando mas que el quimera cuando  no debería ser asi... dejo varias imágenes para explicarme mejor.
https://ibb.co/j94jCk
https://ibb.co/haWmQ5
https://ibb.co/mAHt55
https://ibb.co/hRkfk5
https://ibb.co/gRLrsk
https://ibb.co/i0hhyQ
https://ibb.co/hHFPCk
https://ibb.co/k1vrsk
https://ibb.co/cTzvJQ
https://ibb.co/g6MmQ5
**Que esperas:**
Espero que el quimera funcione correctamente con mi equipo y mi arpen al 80% debería pegar mucho mas puesto que el daño del quimera es daño con arma y la penetración de armadura debería ser un factor para sacar a lucir el daño de esa skill en cambio el punteria deberia estar por debajo del quimera.
**Pasos:**
1. Pegar por tiempo en muñecos para ver que el punteria hace mas que el quimera.

**Comment by el-druida** [comment]
Al daño de quimera tenes que sumarle el daño instant que realiza al renovar picadura

**Comment by Flechero** [comment]
Mi estimado compañero , quimera ,sin el quimera serpiente  siempre ha pegado más que el puntería y eso cualquier caza lo sabe, que el puntería pegue 10k y el quimera solo 8k  veo que el quimera esta mal

**Comment by Demonid** [comment]
Flechero, Disparo de Quimera hace el daño de Arma de tu Pj, no se ve modificado por Arpen de ninguna manera, cuando abres tus estadísticas y ves el rango de daño con arma, ese es el daño de tu quimera, modificado por el % que indique la habilidad + talentos.

La única forma de aumentar el daño de tu disparo de Quimera fuera de los talentos basicos, es colocando el Glifo de Picadura de Serpientes que afecta a la segunda parte del daño de quimera, el daño extra que hace según picaduras,  y en Raids con los Procs de daño que aumentan el daño de arma de tu Pj.

En esta imagen te muestro el daño que debería hacer:

http://i.imgur.com/8uHZ89N.jpg

Según el addon, debería hacer aprox 2122 y termina haciendo 2154 por lo que el daño esta perfecto.
