### ISSUE TITLE
Bug de looteo de items farmeables (menas, flores, desuellos, cofres).

### ISSUE THREAD

**Issue by MuWoW** [Demonid/BugTracker#67]
**Descripción:**
No se puede desollar, ni cojer hierbas, ni menas al minear, y muchos afirman que los cofres no muestran loot. 
**Que esperas:**
Que arreglen este bug horrendo. No todo es ICC.
**Pasos:**
1. Aproximarse a una mena, flor, bestia muerta y dar clic para recoger la hierba, mena o cuero (o abrir cofre en su caso).
2. Al momento de recoger hierba/minear/desollar o abrir cofre no aparece el menú de los ítems farmeados y te aparece el mensaje "ya esta siendo usado" como si estuviese abierto tal menú.
3. No se recoge nada, no se farmea nada. 

Es lamentable ver un bug así a estas alturas del servidor. Lamentable en todo su aspecto y significado de la palabra ya que es algo muy básico para cualquier player gamer en usar su profesión para fomentar el crecimiento del servidor con la venta de sus craftings, el uso correcto de sus profesiones y procs ingame y para mantener a la gente de buena mentalidad dentro de AsuraWoW (como dije, no todo es ICC).

Espero que lo vean a la brevedad, no es un bug de profe 25n, ni un bug de matanza de Stratholme (?) es un bug que de verdad desanima a TODA la población.

![wuzavjy](https://user-images.githubusercontent.com/28643129/27550669-93a69b96-5a6e-11e7-933d-07b429f3e3a9.png)

**Comment by el-druida** [comment]
Solo las cosas de profesiones?

**Comment by MuWoW** [comment]
Según he visto si. Logeé para minear y farmear hierbas / telas y me paso lo que comento. Pregunté a los de mi guild y a gente de mundo el problema y me dieron el dato del desuello y de los cofres. Especial redundancia en el cofre de ahune. El despojo de npcs muertos lo vi bien ya que farmee telas normal en corona.

**Comment by el-druida** [comment]
Si, estoy en este momento dentro del juego ando viendo

**Comment by MuWoW** [comment]
Todos dicen q empezó desde el reset de anoche por el alto delay q había presuntamente debido al mante del host.

**Comment by el-druida** [comment]
En unos momentos se aplica el arreglo, posiblemente mas tarde tambien se reinicien ID's

**Comment by Demonid** [comment]
Gracias por reportar, el fallo ya ha sido solucionado.
