### ISSUE TITLE
Bug cadena de misiones  Hijis de Hodir (Poblado Brunnhildar)

### ISSUE THREAD

**Issue by freelunch2** [Demonid/BugTracker#68]
**Descripción:**
Los Npc estan bug cada vez que sales del poblado Brunnhildar desaparecen
**Que esperas:**
Los Npc deberian  no deberian desaparecer cuando sales del poblado Brunnhildar
**Pasos:**

1. Salir del Poblado Brunnhildar
2. https://scontent.fsst1-2.fna.fbcdn.net/v/t1.0-9/19553942_1946457635638402_8011282479339053789_n.jpg?oh=fd247eb71faae851ea027dd39d543861&oe=59DB1F66
3.  https://scontent.fsst1-2.fna.fbcdn.net/v/t1.0-9/19510221_1946457625638403_7421446589178236889_n.jpg?oh=f6a0a7a7e9cf4003b41c794a1da9476c&oe=59C5402D

**Comment by el-druida** [comment]
?

**Comment by el-druida** [comment]
Seguro que igual que todo mundo, lea aca o sea mas descriptivo.
https://github.com/Demonid/BugTracker/issues/56

**Comment by el-druida** [comment]
Por favor, lea el post https://github.com/Demonid/BugTracker/issues/56 asi comprende que con 99.9% de seguridad es un problema de usted por tener alguna otra mision que le cambia de fase. Y de paso deje de abrir y cerrar.

**Comment by freelunch2** [comment]
Gracias :( Culpa mia <3

**Comment by el-druida** [comment]
Un gusto y por favor pase la voz a otros jugadores que quizas les pase lo mismo sobre esa zona.

**Comment by el-druida** [comment]
Un gusto y por favor pase la voz a otros jugadores que quizas les pase lo mismo sobre esa zona.
