### ISSUE TITLE
Bug Mision Final de la Empuñadura (La purificacion de Quel Dalar)

### ISSUE THREAD

**Issue by itouo** [Demonid/BugTracker#7]
Usas la espada en la fuente, y esperas un momento, no se purifica o cuando la agarras de vuelta, no te completa quest.

**Comment by el-druida** [comment]
Favor de incluir mas datos, como facción. Por otra parte, no logre reproducir la falla excepto forzando comportamientos extraños. Por cierto, si usted esta "tomando" de nuevo la espada y no completa la quest. Significa que esta en grupo de raid. Las misiones normales estando en raid no se completan.

**Comment by OldieButGoldie** [comment]
Hola, ha podido corroborar si estaba en grupo de banda al momento de realizar la misión?

**Comment by el-druida** [comment]
Luego de varias pruebas la mision no presenta problemas. Y dado que el usuario no ha dado mayor feedback, paso a cerrar.
