### ISSUE TITLE
ULTIMA MISION BUG DE LOGRO PJ MIKATAN

### ISSUE THREAD

**Issue by rogger424a** [Demonid/BugTracker#70]
BUenas Noches Tengo este problema
      Descripción:  Bug en mision De señor Escarabajo..... voy haciendo el seguimiento de l mision por un buen tiempo y al finalizar y entregsar la penultima mision para el logro del señor escarabajo y entrega de tanke resonador negro ocurre lo siguiente..... se entrega se completa satisfactoriamente al completarla el npc ni el escudo donde se toco no responde a la mision que deberia dar el logro y la montura en si no aparece Hable con los Mj me recomendaron reportar a bug espero puedan solucionar mi problema MI PJ SE LLAMA MIKATAN jugador experimentado.

**Que esperas:**
Que Me dejen terminar la mision para Obtener el logro y la montura respectiva

"" Pruebas ""
Cetro de MAr de Dunas y arma entregada de la penultima miison

**Comment by el-druida** [comment]
No hay ningun bug, la ultima parte es parte de un evento mensual.
