### ISSUE TITLE
Algunos Bugs en ICC  

### ISSUE THREAD

**Issue by Shermieqtx** [Demonid/BugTracker#71]
Hola Buenas encontré unos posibles bugs dentro de ICC
1.- En el Boss Valithria la dragona hace un movimiento raro y se mueve de su posición inicial a una zona random.
https://puu.sh/wuqJk/271b411d35.jpg.

2.- En la plataforma de LK al momento de pulear el boss o a  los adds (horror) se meten de bajo de la plataforma y lo cual son jodidos pulear y se pone tediosos.
https://puu.sh/wvmbJ/84a1b4fa3f.jpg
https://puu.sh/wvlwr/cc78e1048d.jpg

3.- No se si sea un bug pero al momento de la pelea ( en LK, Esto también pasa con los horrores) El agro se vuelve loco y se va a un target random. Lo cual provoca una muerte estúpida y sin sentido....

Pd: No tengo foto ocuparía vídeo

4.- Encontré esto el boss se reinicia al momento de targetear a uno que lleve la valkyrs. (Esto pasa cuando lk targetea al marcado que lleva la valkyrs) 
https://puu.sh/wvnkg/2f6bae1b77.jpg

Espero les sirva la informacion, Seguimos en contacto 👍

**Comment by el-druida** [comment]
Este tipo de cosas sucede en una raid pura o de facciones mezcladas?

**Comment by Shermieqtx** [comment]
Faccion mezclada

**Comment by el-druida** [comment]
Aha... lo de "dragona" ocurrio solo una vez o varias veces?? que es lo diferente a lo habitual de curar/matar que han hecho?

**Comment by Shermieqtx** [comment]
Ya van varios saves que la dragona se mueve de su posición inicial, Ps normal se hace como cualquier otro  sv, curar, matar  misma historia de siempre..

**Comment by el-druida** [comment]
Especifique? saves se refiere a renovacion de ID o ID limpia desde cero?

**Comment by el-druida** [comment]
Cuanto mas detalles y especificaciones logre dar, mejor. Asi es mas sencillo lograr recrear lo sucedido para asi encontrar la falla. En lo personal, aun no logro replicarlo.

**Comment by Shermieqtx** [comment]
La verdad, no sabría explicar la falla  es algo raro a varios compañeros le ha pasado lo mismo. De pronto serán los portales que se yo :S

**Comment by el-druida** [comment]
¿Como no sabe explicar? Fue una extension de ID o una ID limpia?

**Comment by Shermieqtx** [comment]
Ah Fue id limpio, Como te digo van varios saves..

**Comment by el-druida** [comment]
Me parece que hay errores de concepto...
Vamos de otra manera, la semana pasada ya les paso?

**Comment by Shermieqtx** [comment]
Yep, ya van 2 semanas que pasa este error.

**Comment by OldieButGoldie** [comment]
Hola, detecté varios errores relacionados a Valithria, en el siguiente reinicio programado de servidor debería estar subsanado el inconveniente.

Seguimos revisando LK

**Comment by Shermieqtx** [comment]
También se encuentra en toc este misterioso bug 
https://puu.sh/wzWsR/2e98bb6163.jpg

**Comment by Demonid** [comment]
Ambos fallos están relacionados con Vmaps, los cuales fueron modificados recientemente, estamos trabajando en una solución pero puede que tarde un poco mas en solucionarse.

Apenas tengamos una novedad sobre esto lo informaremos.

**Comment by Demonid** [comment]
Todos los fallos reportados aqui han sido solucionados, a la proxima por favor diferentes reportes para cada fallo para agilizar el proceso.
