### ISSUE TITLE
bug de daño del brujo destru

### ISSUE THREAD

**Issue by darwinhernandez** [Demonid/BugTracker#72]
el daño del brujo destrucción  es un asco el critico mas alto que meto con descarga de las sombras es de 9k cuando lo normal es que sea 15 o 16k y en pvp el caso se nota mucho mas ya que el daño máximo con descarga de la sombras es de 4k bueno en si es el poder con mas daño que hay en el wow y en este caso pega mucho mas el incinerar,igualmente pasa con el conflagar, tiene un daño en critico de 3.5k y en pvp de 2.5k y por favor revisen ese daño cabe destacar que mi poder con hechizo es de 2736 y llega a 3k seguidamente con el bordado de la capa,  un poder con hechizo lo suficientemente estable para que el brujo haga buen daño

**Comment by OldieButGoldie** [comment]
Hola, cuando refiere 
> lo normal es que sea 15 o 16k

En que datos se basa para llegar a esta conclusión? Ha evaluado el coeficiente de Spell power aplicado a Descarga de sombras?

**Comment by Demonid** [comment]
Se cierra tema por falta de información o pruebas retail.
