### ISSUE TITLE
Perdida de Item

### ISSUE THREAD

**Issue by Cruelity** [Demonid/BugTracker#74]
Personaje: Bestworld
Item: Escudo muro de Gladiador Colérico (Perdido el 28/06/2017)
Que esperas: Devolución de Item

Imagen: https://ibb.co/nzp8sk

**Comment by el-druida** [comment]
Como aqui se trata de reportar fallas para luego de haberla, repararla. Seria mas util si diera más datos, como que hizo antes de notar la perdida del item. Cuantos tienen acceso a su cuenta. Relogea muy seguido? Usa el gestor de equipamiento? Estaba solo parado o en raid/duelo/arena? etc etc

**Comment by Cruelity** [comment]
Supondría que habrá sido el gestor de equipamiento, ya que suelo cambiarlo varias veces.
Edit. Y suelo cambiar mi pass diariamente para descartar ese tema.
