### ISSUE TITLE
Bug canal buscar grupo

### ISSUE THREAD

**Issue by Falkenralf** [Demonid/BugTracker#75]
Personaje: Kurosawa
Descripción: Desde hace dos días empecé a tener un problema en el canal4, debido a que puedo ver los mensajes pero no puedo publicar nada en dicho canal. Ya reinicié opciones de chat, borré caché y WTF. Ninguna de las soluciones que me dieron otros personajes funcionó.
Qué esperas: 
- Quese pueda resolver ese bug debido a que mucha gente lo ha tenido y ha habido gente que se ha marchado del servidor o borrado personajes por que los GM's no tiene solución a esta respuesta.

- En caso de que no se pueda resolver, que los GM's promuevan a la creación de nuevos canales para evitar este problema en canales predeterminados del juego como BuscarGrupo.

**Comment by el-druida** [comment]
¿Que version estas usando del juego? es-es? es-mx? enUS? enGB?

**Comment by erkiv** [comment]
a mi me pasa igual por momentos, lo que se me ocurrio fue darle click en la pestaña registro de combate y de ahi regresar a pestaña general y solucionado, al menos eso hago cuando me pasa y se soluciona.
saludos
