### ISSUE TITLE
DK- Talento Sabañones

### ISSUE THREAD

**Issue by sleppy12** [Demonid/BugTracker#76]
**Descripción:**
El talento desaparece del objetivo si este se limpia o disipa la enfermedad "Fiebre de escarcha".
**Que esperas:**
El talento debería de activarse al aplicarse "Fiebre de escarcha" y tener la duración completa independientemente de si tiene o no la enfermedad, ya que no es un hechizo disipable.
**Pasos:**

1. 
2. 
3.

**Comment by Demonid** [comment]
Esto es falso, el funcionamiento correcto es que el debuff de reducción de movimiento sea eliminado al dispelear la enfermedad de escarcha.

Fuente:

http://wow.gamepedia.com/Chilblains

WotLK Patch 3.2.0 (2009-08-04): Icy Clutch can no longer miss when [Frost Fever] hits, however, when Frost Fever is dispelled Icy Clutch will also be dispelled.
