### ISSUE TITLE
Arena

### ISSUE THREAD

**Issue by Shermieqtx** [Demonid/BugTracker#77]
Vea nada mas ✌️ 
Al momento de relogear
https://puu.sh/wAc4I/f28eb456e2.jpg
https://puu.sh/wAca9/480c2d574c.jpg

**Comment by Demonid** [comment]
Curioso, pasa el 100% de las veces?

**Comment by el-druida** [comment]
yo no entendi aparte... para que relogear justo antes que comience una arena.

**Comment by Shermieqtx** [comment]
No solo es relogear, Cuando te saca (wowerror ejemplo)
Y no pasa el 100% de las veces.  Yo se que relogear en medio de una arena es algo innecesario, pero claramente esto no debe pasar ✌️

**Comment by Demonid** [comment]
Probablemente relacionado al Crossfaction Bg, @arks-dev
