### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by bobdragon** [Demonid/BugTracker#78]
**Descripción:**
(la clave de la condenacion la carga de borack)npc ruul el ensombrecedor (desaparecido) 
**Que esperas:**

**Pasos:**

1. 
2. 
3.

**Comment by el-druida** [comment]
https://github.com/Demonid/BugTracker/issues/45

**Comment by el-druida** [comment]
Leyo el otro post sobre la misma quest?

**Comment by el-druida** [comment]
debido a que el jugador no se ha presentado, cierro
