### ISSUE TITLE
El daño del war o solo a mi me pasa( Golpe Mortal Rango 8)

### ISSUE THREAD

**Issue by prodoo987** [Demonid/BugTracker#79]
**Descripción:**
Buenas quiero informar sobre el golpe mortal que baja poco de lo normal no se si a mi nomas me pasa o a otros que utilizar el warrior armas pvp , bueno cada vez que doy golpe mortal este ataque baja menos de 2mil ya que teniendo un buen inicio de arpen ,abalorio de icc 10N y critico deberia bajar 4k con enfurecer y con critico sacaría hasta 5k . Ademas cada vez que me sacan critico no se me activa el talento Manía Sangrienta ya que si recibo un Critico este me regeneraría un 6% de mi salud total durante 6 segundos
**Que esperas:**
Bueno espero que me solucionen no se si a mi nomas me pasa o a los demás, muchas gracias

**Pasos:**

1.  
![prodo 1](https://user-images.githubusercontent.com/29969393/27963138-affd9c48-62f9-11e7-8937-18a144803c4a.jpg)

2. 
![prodo 2](https://user-images.githubusercontent.com/29969393/27963145-b5f23fc8-62f9-11e7-939d-ec5358871af7.jpg)

3. 
![prodo 3](https://user-images.githubusercontent.com/29969393/27963153-bac4fafe-62f9-11e7-9c49-4d4247272d30.jpg)

**Comment by Demonid** [comment]
Buenas, podrias mostrar la formula en la que te basas para decir que el daño deberia ser 4k con enfurecer y hasta 5k con critico ?
