### ISSUE TITLE
Bug foso de Saron Mision

### ISSUE THREAD

**Issue by kokito123** [Demonid/BugTracker#8]
Al completar la misión de foso y terminar (LIBERACIÓN DE FOSO) jaina a la que tengo que entregar la misión. se pone a pelear con los esclavos de foso y no me deja entregar misión. Esta bug T_T.

Pdt- Soy alianza y hice foso con la alianza, no tengo fotos x que no se como subirlas : /.

**Comment by el-druida** [comment]
Se esta revisando, por cierto a la hora que inicia el evento antes de bajar el boss... aparece el lider alianza de los esclavos o el orco? Y segundo, llevan el boss al tunel? si es asi... el evento es para que no hagan eso

**Comment by eljudaz** [comment]
buenas tardes no supe como poner un tiket aparte pero por este medio quiero informar  sobre el bug de mi dk no puedo invocar la mascota desde ayer, espero alguien me ayude a repararla por favor. saludos

**Comment by kokito123** [comment]
Bueno al comensar normal sale jaina y los campeones del torneo argenta para matar a tyranus y todo eso.
Cuando llegamos al ultimo boss (tyrannus) vienen jaina 1 orco algunos npc orcos y aliz dicen los ayudaremos heroes,etc. al matar a tyrannus los esclavos (aliz y hordas) vivos pelean con jaina.
En una que fui ni los esclavos ni jaina se peleaban entre ellos aun asi no se podia entregar la mision.

**Comment by el-druida** [comment]
¿Que campeones de toc? O_o
Igualmente ya se han hecho modificaciones que deberian ser aplicadas de un momento a otro.

**Comment by kokito123** [comment]
los npc normalmente que salen al inicio en la puerta

**Comment by kokito123** [comment]
supongo que son de toc xD. Eso espero. llevo dias intentando completar la mision T_T.

**Comment by OldieButGoldie** [comment]
@eljudaz Por favor cree un reporte nuevo, mantengamos el tracker limpio

Un saludo
