### ISSUE TITLE
Perdida de items #2

### ISSUE THREAD

**Issue by Cruelity** [Demonid/BugTracker#80]
PJ:Bestworld
Pido una recuperación de items de la Hora 3:00 am Servidor...................

**Comment by Demonid** [comment]
Podrias dejar una lista de los items perdidos ?

**Comment by Cruelity** [comment]
1. Zapatillas suaves de Taldaram 
2.Escorpión incrustado de agujas
Día Martes 2:30-3:00 am No tan exacto el tiempo de repentina desaparición de items
y ... Escudo muro de Gladiador colérico (que hace semanas reporte que había desaparecido..)

**Comment by Demonid** [comment]
Solucionado.
