### ISSUE TITLE
Bugs icc

### ISSUE THREAD

**Issue by Shermieqtx** [Demonid/BugTracker#81]
1.- En la pelea "Caraputrea" los charcos de  la pelea se desaparecen al  pisarlos  y no ralentizan..
https://puu.sh/wHwga/428c39fe13.jpg
https://puu.sh/wHwg2/ae0e217119.jpg

2.- En la pelea de Lk. En la fase de la valkyr Al tirar CÓLERA SAGRADA la animación de las valkyrs no Stonea avanzan  de frente. (Mas bien las Stonea pero da igual de nada sirve).. 
pd: No tengo pruebas pero es fácil de detectar.

Gracias por su tiempo

**Comment by Demonid** [comment]
Ambos fallos los probaste durante el save actual? 10 de Julio a 16 de Julio?

**Comment by Demonid** [comment]
Gracias por reportar, empiezo a investigar

Devs:

1- El fallo de Caraputrea esta confirmado y proviene de TC.
2- El fallo de las Valkyr esta pendiente por comprobar, sin embargo creo tener una idea de lo que lo causa y un posible arreglo.

@arks-dev
