### ISSUE TITLE
Bug Misiles Arcanos.

### ISSUE THREAD

**Issue by koujou1** [Demonid/BugTracker#82]
**Descripción:** Los Misiles Arcanos del mago al ser el primer golpe a una criatura que no esta con combate, lo "agrean" pero esta se queda quieta, y empieza  a regenerar vida, como si no estuviera en combate, es con la única habilidad que pasa esto, probé desde la explosión arcana, pirofrios y descargas de escarcha, pero es la única con la que pasa esta particularidad.
 
Lo mas lógico es que al tirar una habilidad la criatura (sea agresiva o no) se abalance sobre un.

**Pasos a realizar:** Es muy simple realizar esto la única condición es que los Misiles Arcanos sean la primera habilidad en ser casteada. En las criaturas pisavas (barra de vida amarilla) desde cualquier distancia pasa esto; en el caso de las agresivas (barra de vida roja) para evitar que la misma ataque por su naturalidad yo acostumbro hacerme a una distancia que no me ataque, generalmente máximo rango.

![wowscrnshot_071317_005011](https://user-images.githubusercontent.com/30138798/28152502-7e103d96-6766-11e7-9301-e734a51662cd.jpg)
![wowscrnshot_071317_005017](https://user-images.githubusercontent.com/30138798/28152503-7e160686-6766-11e7-9302-380279975a82.jpg)
![wowscrnshot_071317_004843](https://user-images.githubusercontent.com/30138798/28152557-c61cb696-6766-11e7-9386-4fcd122d65f7.jpg)

Como podrás ver, que como tal no me marca como si estuviera en combate, puedes ver que puedo montarme en la montura y demás en el lado derecho que es donde las tengo ubicadas.

**Comment by Demonid** [comment]
Relacionado:

https://github.com/TrinityCore/TrinityCore/issues/18259

@arks-dev
