### ISSUE TITLE
Maestria elemental del chaman "Rayos" BUG

### ISSUE THREAD

**Issue by Deathpaul** [Demonid/BugTracker#83]
**Descripción:**
Lo uso y no muestra el cd que tiene para ser reutilizada, sigue con color la skill
**Que esperas:**
Que funciones con el coldDown visual respectivo
**Pasos:**

1. Usar Maestria Elemental
2. Cargar el Cd de maestria como cualquier otra skill
3. Tomarse la sopita y sus vegetales.

**Comment by Demonid** [comment]
A ver si entendi...

Activo el hechizo Maestria Elemental pero no hago uso de la habilidad, espera a que pase el cooldown y no muestra el CD?

----

Primera imagen: Uso la habilidad Maestria Elemental y espero a que los Buff (Ambos) caduquen, los puedes ver en la parte de arriba derecha.

http://i.imgur.com/sTYfeHf.jpg

El Buff caduca y el cooldown se activa, empezando el contador para volver a utilizarlo.

http://i.imgur.com/i53ROao.jpg

Si es esto lo que me reportas, esta funcionando correctamente, y si entendi mal, por favor deja mas detalles sobre el problema, si puedes una imagen donde pueda analizar el fallo.

**Comment by Deathpaul** [comment]
Eso mismo era, gracias.

**Comment by Demonid** [comment]
Paso a cerrar el tema ya que el fallo no existe, saludos!
