### ISSUE TITLE
Bug Druida levita al usar Forma de Vuelo al salir del agua.

### ISSUE THREAD

**Issue by koujou1** [Demonid/BugTracker#85]
**Descripción:** Hace ya un tiempo mientras farmeaba plantas con mi druida, me pasaba que al salir del agua saltando para poder activar la forma de vuelo directamente, el druida se quedaba en un estado como de levitación, pero este estado ocurría sin la forma de vuelo. La Druida se quedaba flotando en su forma normal y podía moverse a gusto en cualquier dirección, hasta en montura te puedes poner y para quitar esta situación bastaba con volver a activar la forma de vuelo.

Lo normal seria que al salir del agua y cambiar de forma, es que siguieras con normalidad transformado en Ave y seguir tu rumbo.

**Pasos:**
1. Estar en un cuerpo de agua, a mi me ha pasado tanto en lugares donde se puede caminar, como en lugares que son profundos y solo se nada.
2. Obviamente estar en una zona donde se pueda volar.
3. Estando en limite entre el agua y el aire, saltar y cambiar a forma de vuelo. Si es una zona donde se puede caminar pero hay agua debería bastar con cambiar de forma.

![wowscrnshot_071517_063418](https://user-images.githubusercontent.com/30138798/28239042-01cbbb16-6928-11e7-99b2-5ad8d9f74437.jpg)
![wowscrnshot_071517_064132](https://user-images.githubusercontent.com/30138798/28239076-ade192ea-6928-11e7-9b38-6563d6f6aba6.jpg)

**Comment by Demonid** [comment]
A la noche me explicas ingame como reproducir el fallo, que este es uno de esos fallos que apenas viendolos en tiempo real se pueden entender.

**Comment by Demonid** [comment]
Reparado tras el proximo mantenimiento.
