### ISSUE TITLE
Bug buscador de mazmorras aleatoreas.

### ISSUE THREAD

**Issue by koujou1** [Demonid/BugTracker#86]
**Descripción:** Este bug posiblemente sea meramente visual, o tal vez el buscador como tal no este en el correcto funcionamiento. Por costumbre al ir a farmear yo siempre me pongo en cola en el buscador de mazmorras aleatorias, pero note hace poco que al revisar en la cola, el buscador no me marca que funciones (otros jugadores con alguna función Tank, Heal, Dps) esten en cola, ni tampoco la funcion mia. 

Por lo menos del server de donde vengo estoy acostumbrado a que me marque, o mejor dicho se ilumine el respectivo icono de las funciones que hay en cola en el buscador.

**Pasos:** Pasos? es solo poner cola a Mazmorras aleatorea solo.

En esta imagen se puede ver como a pesar de decirme el buscador que estoy en cola como DPS, no me marca como tal.
![wowscrnshot_071517_065512](https://user-images.githubusercontent.com/30138798/28239146-9792ed16-692a-11e7-9b65-22cd095b3f20.jpg)

Esta otra es una imagen que encontre que explica mas facilmente a lo que me refiero.
![cola buscador de mazmorra](https://user-images.githubusercontent.com/30138798/28239158-cebb887a-692a-11e7-8776-4b3652070f92.jpg)

**Comment by Demonid** [comment]
Gracias por reportar

@arks-dev, sera algo que quedo pendiente del porteo del LFG de SC no ?
