### ISSUE TITLE
Bug quest "Un monumento a los caidos" en cumbres tormentosas

### ISSUE THREAD

**Issue by Deathpaul** [Demonid/BugTracker#87]
**Descripción:**
No está el npc para terminar la quest Njormeld
**Que esperas:**
Que el npc aparezca debido a que da otras misiones
**Pasos:**

1. Aparecer el npc
2. Completar quest
3. Continuar las quest para seguir sacando reputación

**Comment by el-druida** [comment]
Necesito ID de quest por favor asi como el ID del npc por favor, tambien el detalle de faccion de usted. Por las dudas mientras tanto revise si no tiene alguna otra mision que le este causando faseo como alguna diaria de toc u otra de las zona de cumbres. Si es el caso que encuentre alguna, abandonela relogee y deberia ver el npc.

**Comment by el-druida** [comment]
Bueno, el npc si ESTA. Vuelvo a repetir que revise sino posee alguna otra mision o item que le cause un cambio de fase. O quizas sino se salteo algo en la zona.

**Comment by el-druida** [comment]
debido a la falta de feedback de parte del usuario, cierro
