### ISSUE TITLE
Daño blanco con las clases melee: picaro

### ISSUE THREAD

**Issue by rherrera123** [Demonid/BugTracker#88]
El daño blanco de la clase pícaro difiere de las estadísticas mostradas en la ventana del personaje

Osea si tengo 40% de crítico deberían mis 40 golpes de cada 100 ser críticos y no es así

**Comment by rherrera123** [comment]
Aquí una maten con datos
https://drive.google.com/file/d/0B7EbIzJKzGdGQlNTYW5oNFhjTzg/view?usp=drivesdk

2000 golpes para cerca del 99% + de confianza, según lo que aprendí en clase de estadística

**Comment by Demonid** [comment]
El problema es que existen 4 posibles resultados, si solo se tratara de Golpe Normal y Golpe Critico, 400 de cada 1000 ataques PODRIAN ser criticos.

Sin embargo aca existen otros 2 posibles resultados, Glancing o Miss, y probablemente varios de estos golpes hubieran sido criticos de no haber fallado o o afectados por glancing (Glancing es un golpe que pega pero tiene su daño reducido.

Personalmente y en vista de que en tu imagen, creo que la cantidad de criticos es la correcta.

De 2130 autoataques, 503 fueron glancing, 168 fueron fallados.

Esto hace que solo los 777 golpes normales y 682 golpes criticos sean validos, sumados son 1459

Y si 1459 es el 100% de ataques que podrian tener la posibilidad de ser categorizados como criticos, 682 lo fueron, eso quiere decir que el 46.74% de tus ataques validos, fueron criticos.

Sin embargoooooooo, @arks-dev probablemente te pueda dar una respuesta mas convincente que yo, asi que lo dejaremos en sus manos.

**Comment by rherrera123** [comment]
Bueno gracias
