### ISSUE TITLE
Bug misión: Lo sagrado y lo Corrupto.

### ISSUE THREAD

**Issue by Cruelity** [Demonid/BugTracker#89]
Acabo de completar el requisito para la misión de lo Sagrado y lo corrupto por el arma Filo de las sombras, pero como puede ver aquí la tengo completa
https://ibb.co/j41pja
Pero cuando quiero canjear los items me aparece en gris y no puedo continuar la misión
https://ibb.co/ikYS4a
Ya borre cache y me sigue apareciendo el mismo error.

**Comment by el-druida** [comment]
puso los items en el banco?

**Comment by Cruelity** [comment]
Como esta en la imagen tengo las 25 Saronitas, Las 2 Sangres y ''Venganza de la luz'' en mi inventario, pero sigue apareciendo gris para continuar...

**Comment by el-druida** [comment]
puso los items en el banco? mientras reunia lo faltante

**Comment by el-druida** [comment]
cri cri cri
Bueno, esto pasa cuando algun item lo puso en el banco. Abandona y retoma la quest, las sangres no se borran por que dejes la mision.

**Comment by el-druida** [comment]
Solo debera retomar el item "venganza de la luz" que es lo unico que se borra al abandonar la mision.

**Comment by Demonid** [comment]
Si en 2 dias mas este tema no tiene seguimiento, lo dare pore cerrado.

**Comment by el-druida** [comment]
Ya hoy hay que darlo por cerrado, ayer se me paso
