### ISSUE TITLE
Bug Invocar Manáfago (Pet Brujo)

### ISSUE THREAD

**Issue by TheJosu95** [Demonid/BugTracker#9]
Cuando invoco dicha pet ni si quiera aparece, me gasta y genera un fragmento de alma. (Dato: cuando una pet genera un fragmento de alma es cuando se va muy lejos o cosas por el estilo).

**Comment by OldieButGoldie** [comment]
Hola, solucionado junto con #10. Será aplicado en el próximo reinicio.

Gracias por el reporte
