### ISSUE TITLE
Mision Bug : Amenaza desde el Cielo

### ISSUE THREAD

**Issue by nomepulsees** [Demonid/BugTracker#91]
**Descripción:**
La misión " Amenaza desde el Cielo"  no se puede completar.
Los bombarderos deberían bajar pero no bajan y no se les puede dar focus.
**Que esperas:**
La misión se debería realizar de la siguiente manera:
Los bombarderos que están montados sobre el Dragón bajan luego de cojer agro.
**Pasos:**

1. Los Bombarderos te lanzan bombas.
2. Los Bombarderos bajan a pelear.
3. Luego de matar a los bombarderos, Matar el Dragón y listo.

**Comment by el-druida** [comment]
¿Cuantas veces lo intento? Cuando ataco al dragon este tenia los 3 bombarderos montandolo?

**Comment by nomepulsees** [comment]
lo intente alrededor de una hora. Y el dragón solo tenia un bombardero encima.

**Comment by el-druida** [comment]
Ok, entonces el dragon ha quedado activo de alguien que intento matarlo antes. Cuando este respawnea, lo hace con los 3 "cultist" pero si usted o el jugador que intento matarlo mueren, el dragon entra en evadir asi como los bombarderos q se hayan activado y regresan al punto de spawn. El dragon, en caso que alguno ya se habia bajado, retoma su recorrido sin los bombarderos. 
Hagame el favor, si sabe el recorrido del dragon de fijarse si es asi. Que en el lugar de spawn esten los bombarderos previos

**Comment by el-druida** [comment]
Bien, mas alla de las cosas, encontre una falencia. Ya subo el fix para esta mision luego sera aplicado.

**Comment by nomepulsees** [comment]
El recorrido del Dragón es en circulo, no se aleja mucho solo rodea casi en su mismo lugar, lo e seguido por todo su recorrido pero no aparece ningún bombardero aparte del que ya esta encima.
Agradecería mucho si la reparan. Ya que es una misión Diaria de la Cruzada Argenta, muy importante a mi parecer, de todas maneras Gracias.

**Comment by el-druida** [comment]
leyo mi ultimo comentario?

**Comment by nomepulsees** [comment]
Gracias. Saludos :)
