### ISSUE TITLE
La forja del destino

### ISSUE THREAD

**Issue by rherrera123** [Demonid/BugTracker#92]
No sé puede fundir nada en la forja del destinoya saben se llama la forja por algo creo. Debería tener una forja

Si puedes poner una demonid allí sería bacán te doy +1

**Comment by rherrera123** [comment]
Aquí foto para llamar la atención
https://drive.google.com/file/d/0B7EbIzJKzGdGRUQxV0xlcW9OU1E/view?usp=drivesdk

**Comment by rherrera123** [comment]
Más específico: en Dalaran , en el mercado de magos, el cuarto llamado Forja del Destino no sirve para fundir metales de minería, y aunque no estoy del todo seguro, creo que sí se debería poder fundir minerales.

**Comment by Demonid** [comment]
Segun http://wow.gamepedia.com/Forge_of_Fate y http://wowwiki.wikia.com/wiki/Forge_of_Fate, en esa area tanto mineros, herreros e ingenieros pueden utilizarla para sus crafteos.

Sin embargo me es imposible encontrar alguna prueba sobre si alguna vez se pudo utilizar de esta manera en el oficial, actualmente esta forja tampoco te permite craftear en el oficial.

Personalmente no tengo ningun problema en darle esta opcion a los jugadores, pero es @el-druida quien se encarga de este tipo de cosas, asi que sera lo que el decida.

**Comment by el-druida** [comment]
eeemmm pero si las demas si andan... porque esa si o si? .-.

**Comment by rherrera123** [comment]
Esque solo hay una donde los mineros y da flojera ir al yunque en otro lado, sólo digo sería bueno que pudieran una forja allí. Es mi opinión, no le he preguntado ni hablado con nadie más sobre esto. Gracias

**Comment by rherrera123** [comment]
Y leyendo detenidamente el comentario de @Demonid , esas fuentes dicen que mineros craftean sus cosas allí.
Y los mineros lo único que pueden hacer es fundir minerales.

**Comment by el-druida** [comment]
....no es blizzlike, listoooo pasando a otra cosa (?

**Comment by Demonid** [comment]
En vista de que no es Blizzlike, cierro tema.
