### ISSUE TITLE
bug  de manos de ingeneria

### ISSUE THREAD

**Issue by psicopata** [Demonid/BugTracker#93]
al parecer no se puede usar mi guantes de ing , en icc solo pasa esto
**Descripción:**
![sin titulo](https://user-images.githubusercontent.com/28879392/28487853-55173754-6e60-11e7-8a3b-1e0e6b5f3f73.png)

**Comment by el-druida** [comment]
Ya se aclaro una vez esto, es por el tema de facciones y el cross. Esa raid era mixta?? o sea hordas y alianzas mesclados?

**Comment by psicopata** [comment]
obio es mixta como todas las demas

**Comment by Demonid** [comment]
El tema es que cuando entras en una Raid Mixta, tu faccion cambia, y por ello no puedes usar un hechizo de un item que es de la faccion contraria.

Te recomiendo cambiar los Guantes por unos de ICC apenas tengas la posibilidad, de esa manera podras activar el enchant cuando quieras.
