### ISSUE TITLE
Equipo (items) Desaparecido.

### ISSUE THREAD

**Issue by Wily1260** [Demonid/BugTracker#95]
**Descripción:**  Mi equipamiento de tanque ha desaparecido(items de tank), como se viene oyendo casos de desaparición de items creo que ya no soy ajeno a este. Me acaba de suceder a mí. Anoche domingo jugué con normalidad, hoy lunes al conectar mi pj y querer hacer la mazmorra diaria mi equipamiento de tanque no estaba.

**Que esperas:**
Que el encargado de este problema lo solucione mas pronto posible ya que ningún usuario es consciente de lo que no debe hacer para que el equipamiento se lo borre excepto usar el gestor de equipamiento.

Que el GM encargado reponga los items perdidos ya que ya es casi  1 mes que oí acerca de este problema y aún sigue pasando. Cae bajo la responsabilidad del equipo de trabajo del servidor los arreglos y evitar que estas cosas pasen.

**Pasos:**

1. No usar el gestor de equipamiento. Aunque no es 100% confiable ya que yo no lo uso y aun así desaparecieron mis items.
2. Para cualquier cosa o tema de conversación acerca de este asunto comunicarse INGAME conmigo bajo el nick de Papatank.
3.

**Comment by Demonid** [comment]
No dejaste el nombre del Pj que perdio los items, lo necesito para poder ayudarte, apenas conecte esta tarde te ayudo.

**Comment by Wily1260** [comment]
el pj es Papatank, los items volvieron pero no las gemas ni enchats hoy que en día el farmeo de gemas por honor esta dura :(

**Comment by el-druida** [comment]
Porque son items nuevos que el sistema recupero al detectar una perdida. Sea duro o no el farmeo me parece que es peor no tener nada.

**Comment by Wily1260** [comment]
perdida que se pudo evitar a su tiempo ¬¬

**Comment by Demonid** [comment]
Los items te los devolvi yo anoche antes de irme, al menos los que logre verificar que no tenias en un Backup del dia 23, las gemas y enchants te tocara ponerlas tu.
