### ISSUE TITLE
Desparicion de equipo

### ISSUE THREAD

**Issue by Wily1260** [Demonid/BugTracker#96]
Descripción: Mi equipamiento de tanque ha desaparecido(items de tank), como se viene oyendo casos de desaparición de items creo que ya no soy ajeno a este. Me acaba de suceder a mí. Anoche domingo jugué con normalidad, hoy lunes al conectar mi pj y querer hacer la mazmorra diaria mi equipamiento de tanque no estaba.

Que esperas:
Que el encargado de este problema lo solucione mas pronto posible ya que ningún usuario es consciente de lo que no debe hacer para que el equipamiento se lo borre excepto usar el gestor de equipamiento.

Que el GM encargado reponga los items perdidos ya que ya es casi 1 mes que oí acerca de este problema y aún sigue pasando. Cae bajo la responsabilidad del equipo de trabajo del servidor los arreglos y evitar que estas cosas pasen.

Pasos:

No usar el gestor de equipamiento. Aunque no es 100% confiable ya que yo no lo uso y aun así desaparecieron mis items.
Para cualquier cosa o tema de conversación acerca de este asunto comunicarse INGAME conmigo bajo el nick de Leonidas.

**Comment by Demonid** [comment]
Necesito los siguientes datos:

Links de Items perdidos:
Ultimo fecha en la que viste los Items
Pj que perdio los items.
