### ISSUE TITLE
Llave karazhan mision bug

### ISSUE THREAD

**Issue by crackcocaine** [Demonid/BugTracker#97]
Pz miren estaba haciendo la cadena de misiones para poder obtener la llave de karazhan y poder 
     sacar logrito y tambien entrar ala mazmorra por la montura.
      - haber si me reinician las misiones para hacerla otra vez o pz me dan la llave ya que la mision que 
        habia hecho una de  las ultima para que me la entreguen
      haciendo la cadena de misiones llego a [http://es.wowhead.com/quest=9837/regresa-junto-a-khadgar](url) es una mision en cavernas del tiempo donde tengo que hacer toda la mazmorra para poder hablar con el npc y me de una llave pero al hacer todo esto hablo con el npc y no me entrega ninguna misión mas así que se rompe la cadena de mision y ya no se puede continuar para sacar la llave.

haber si me reinician las misiones para hacerlas otra vez o me dan la llave  que casi complete todas las misiones tal vez no tengan tiempo pero loco asi uno se distrae ya que icc es una vez por semana y asi se mata el tiempo haciendo retroraids y logritos gracias ATT: Crackcocaine

- o si no me dan la siguiente mision que sigue la cual es pero tendrian que darme los restos de la llave de la mision anterior que esta en el link de arriba [(http://es.wowhead.com/quest=9838)](url)
y asi poder continuar con las misiones.

**Comment by el-druida** [comment]
Esto es contenido legacy que siempre ha funcionado. La mision que mencionas solo empieza en Cavernas del Tiempo, no termina "ahi".

**Comment by el-druida** [comment]
Pues la quest 9837 no tiene ningun problema, acabo de probarla en el servidor de desarrollo como en el live.  Sera mejor que revise guias en lugar de achacar a la mision en si.

**Comment by el-druida** [comment]
Bien, debido a la falta de feedback de parte del usuario paso a cerrar.

**Comment by crackcocaine** [comment]
pz loco vi varias guias y en teoria como dices tiene que darme la siguiente mision en cavernas pero no lo hace se queda como un signo de interrogacion y no me da nada =(

**Comment by el-druida** [comment]
Dices que llegaste a la mision 9837 y no la puedes completar. Es raro porque es una mision autocompletable que se entrega en SHATTRAH, te la da el mago dentro de la mazmorra del pantano en cavernas del tiempo que te manda a la otra ciudad.

**Comment by crackcocaine** [comment]
si se supone que me la tiene que dar pero no me la da se acaba ahi y no puedo seguir con la cadena por eso es que hice el reporte =( haber si me ayudan
