### ISSUE TITLE
Misión Bug by: Lia

### ISSUE THREAD

**Issue by Hyeminc** [Demonid/BugTracker#98]
Mision de Cazador
 [El báculo de los Ancestros] 
**Descripción:**
No se puede Conseguir la Cabeza de Solenor, El Npc-Demonio, no se transforma, lo cual impide que caiga la cabeza de Solenor.
**Que esperas:**
Lo Encontraría Caminando, lo atacaría, y después que se debilite se transformaría en demonio, luego de matarlo Soltaría la Cabeza de Solenor
**Pasos:**
Matar al Npc, y no dejar que se transforme en Demonio

**Comment by el-druida** [comment]
Mmmm raro, revisare

**Comment by Hyeminc** [comment]
estoy ahora mismo frente a el, por décima vez lo intentare matar incitándolo a transformarse, pero nada de nada 7w7

**Comment by el-druida** [comment]
dejame el nick de tu pj, espera un momento online q logeo para ver

**Comment by Hyeminc** [comment]
Cazadora
80
Lia
Elfa de Noche

**Comment by el-druida** [comment]
Bien, el faltante de script ya esta subsanado en el servidor DEV. Supongo que se aplicara cuando haya un reinicio.

**Comment by Hyeminc** [comment]
gracias, aqui esperando el reinicio para completar la misión *-*/

2017-07-31 12:35 GMT-05:00 Abraxx <notifications@github.com>:
