### ISSUE TITLE
Item Perdido

### ISSUE THREAD

**Issue by fediebio** [Demonid/BugTracker#99]
Desaparición de Ítem 

**Descripción:**
Se Desapareció un ítem que me tradearon, después de re-logear el ítem desapareció
**Que esperas:**
Que se pueda Solucionar c:

Día de Desaparición 01/08/17 23hrs Aprox.
Item : https://www.terra-golfa.com/extras/terrahead/Hulneth/?item=50705
Nombre Del Ítem :  Guardapolvo ensangrentado del profesor
Personaje que tenia el ítem : Lia

**Comment by Demonid** [comment]
Solucionado, gracias por reportar.
